# Fujitsu Platform Support
obj-$(CONFIG_SND_MB8AC0300_PCM) += mb8ac0300_pcm.o
obj-$(CONFIG_SND_HDMI_PCM) += hdmi_pcm.o
obj-$(CONFIG_SND_F_SAIF_I2S) += f_saif.o
obj-$(CONFIG_SND_SOC_MB86S70_HDMI_DAI) += f_hdmi_dai.o

# mb8ac0300 board Support
obj-$(CONFIG_SND_SOC_MB8AC0300_ADAU1361) += mb8ac0300_adau1361.o

# mb86s70 board Support
obj-$(CONFIG_SND_SOC_MB86S70_WM8973) += mb86s70_wm8973.o

# Fujitsu Machine Support
obj-$(CONFIG_SND_SOC_MB86S70_HDMI) += f_hdmi_card.o
