# SPDX-License-Identifier: GPL-2.0-or-later
obj-$(CONFIG_REALTEK_SOC) += chip.o
obj-$(CONFIG_REALTEK_SB2) += sb2.o
obj-$(CONFIG_REALTEK_SCPU) += scpu.o
obj-$(CONFIG_REALTEK_PM_DOMAINS) += powerctrl.o
obj-$(CONFIG_REALTEK_MCP) += rtk_mcp.o rtk_sha1.o
obj-$(CONFIG_ARCH_RTD129x) += rtd129x_lockapi.o
