/*
 * f_mipidsi1_lp MIPI DSI PHY driver
 * Copyright (C) 2013 Linaro, Ltd for Fujitsu Semi
 * Author: Andy Green <andy.green@linaro.org>
 */

#ifndef ___LINUX_VIDEO_F_MIPIDSI1_LP_H__
#define ___LINUX_VIDEO_F_MIPIDSI1_LP_H__

enum {
	FMDSI_VERSION_OFS = 0,		/* controller version 0x3131302a */
	FMDSI_PWR_UP_OFS = 4,		/* core power up */
	FMDSI_CLKMGR_CFG_OFS = 8,	/* internal clock dividers */
	FMDSI_DPI_CFG_OFS = 0xc,	/* DPI interface configuration */
	FMDSI_PCKHDL_CFG_OFS = 0x18,	/* Packet handler configuration */
	FMDSI_VIDMODE_CFG_OFS = 0x1c,	/* Video mode configuration */
	FMDSI_VID_PKT_CFG_OFS = 0x20,	/* Video packet configuration */
	FMDSI_CMD_MODE_CFG_OFS = 0x24,	/* Command mode configuration */
	FMDSI_TMR_LINE_CFG_OFS = 0x28,	/* Line timer configuration */
	FMDSI_VTIMING_CFG_OFS = 0x2c,	/* Vertical timing configuration */
	FMDSI_PHY_TMR_CFG_OFS = 0x30,	/* D-PHY timing configuration */
	FMDSI_GEN_HDR_OFS = 0x34,	/* Generic packet header config */
	FMDSI_GEN_PLD_DATA_OFS = 0x38,	/* Generic payload data in / out */
	FMDSI_CMD_PKT_STATUS_OFS = 0x3c, /* Command packet status */
	FMDSI_TO_CNT_CFG_OFS = 0x40,	/* Timeout timers configuration */
	FMDSI_ERROR_ST1_OFS = 0x48,	/* Interrupt status 1 */
	FMDSI_ERROR_MSK1_OFS = 0x50,	/* Inetrrupt MASK = ST1 */
	FMDSI_PHY_RSTZ_OFS = 0x54,	/* D-PHY reset control */
	FMDSI_PHY_IF_CFG_OFS = 0x58,	/* D-PHY interface configuration */
	FMDSI_PHY_IF_CTRL_OFS = 0x5c,	/* D-PHY PPI interface control */
	FMDSI_PHY_STATUS_OFS = 0x60,	/* D-PHY PPI status interface */
	FMDSI_LP_CMD_TIM_OFS = 0x70,	/* Low Power command timing config */
	FMDSI_PHY_SETUP_CL_OFS = 0x400,	/* D-PHY setup registers clock lane */
	FMDSI_PHY_SETUP_DL_OFS = 0x404	/* D-PHY setup registers data lane */
};

enum video_mode_type {
	DPIVMC_NON_BURST_SYNC_PULSE,
	DPIVMC_NON_BURST_SYNC_EVENT,
	DPIVMC_BURST,
	DPIVMC_BURST_DUPE
};

enum dpi_color_coding {
	DPICC_16BPP_1,
	DPICC_16BPP_2,
	DPICC_16BPP_3,
	DPICC_18BPP_1,
	DPICC_18BPP_2,
	DPICC_24BPP,
	DPICC_24BPP_DUPE1,
	DPICC_24BPP_DUPE2,
};

enum {
	FMDSI_PWR_UP__SHUTDOWNZ__SHIFT = 0,
	FMDSI_PWR_UP__SHUTDOWNZ__MASK = 1,

	FMDSI_CLKMGR_CFG__TO_CLOCK_DIV__SHIFT = 8,
	FMDSI_CLKMGR_CFG__TO_CLOCK_DIV__MASK = 0xff,
	FMDSI_CLKMGR_CFG__TXESC_CLOCK_DIV__SHIFT = 0,	/* 0 and 1 kill clock */
	FMDSI_CLKMGR_CFG__TXESC_CLOCK_DIV__MASK = 0xff,

	FMDSI_DPI_CFG__EN18LOOSELY__SHIFT = 10,
	FMDSI_DPI_CFG__EN18LOOSELY__MASK = 1,
	FMDSI_DPI_CFG__COLORM_ACT_LOW__SHIFT = 9,
	FMDSI_DPI_CFG__COLORM_ACT_LOW__MASK = 1,
	FMDSI_DPI_CFG__SHUTD_ACT_LOW__SHIFT = 8,
	FMDSI_DPI_CFG__SHUTD_ACT_LOW__MASK = 1,
	FMDSI_DPI_CFG__HSYNC_ACT_LOW__SHIFT = 7,
	FMDSI_DPI_CFG__HSYNC_ACT_LOW__MASK = 1,
	FMDSI_DPI_CFG__VSYNC_ACT_LOW__SHIFT = 6,
	FMDSI_DPI_CFG__VSYNC_ACT_LOW__MASK = 1,
	FMDSI_DPI_CFG__DATAEN_ACT_LOW__SHIFT = 5,
	FMDSI_DPI_CFG__DATAEN_ACT_LOW__MASK = 1,
	FMDSI_DPI_CFG__DPI_COLOR_CODING__SHIFT = 2,
	FMDSI_DPI_CFG__DPI_COLOR_CODING__MASK = 7,
	FMDSI_DPI_CFG__DPI_VID__SHIFT = 0,		/* virtual channel */
	FMDSI_DPI_CFG__DPI_VID__MASK = 3,

	FMDSI_PCKHDL_CFG__EN_EOTP_TX__SHIFT = 0,
	FMDSI_PCKHDL_CFG__EN_EOTP_TX__MASK = 1,

	FMDSI_VIDMODE_CFG__LPCMDEN__SHIFT = 12,
	FMDSI_VIDMODE_CFG__LPCMDEN__MASK = 1,
	FMDSI_VIDMODE_CFG__FRAME_BTA_ACK__SHIFT = 11,
	FMDSI_VIDMODE_CFG__FRAME_BTA_ACK__MASK = 1,
	FMDSI_VIDMODE_CFG__EN_NULL_PKT__SHIFT = 10,
	FMDSI_VIDMODE_CFG__EN_NULL_PKT__MASK = 1,
	FMDSI_VIDMODE_CFG__EN_MULTI_PKT__SHIFT = 9,
	FMDSI_VIDMODE_CFG__EN_MULTI_PKT__MASK = 1,
	FMDSI_VIDMODE_CFG__EN_LP_HFP__SHIFT = 8,
	FMDSI_VIDMODE_CFG__EN_LP_HFP__MASK = 1,
	FMDSI_VIDMODE_CFG__EN_LP_HBP__SHIFT = 7,
	FMDSI_VIDMODE_CFG__EN_LP_HBP__MASK = 1,
	FMDSI_VIDMODE_CFG__EN_LP_VACT__SHIFT = 6,
	FMDSI_VIDMODE_CFG__EN_LP_VACT__MASK = 1,
	FMDSI_VIDMODE_CFG__EN_LP_VFP__SHIFT = 5,
	FMDSI_VIDMODE_CFG__EN_LP_VFP__MASK = 1,
	FMDSI_VIDMODE_CFG__EN_LP_VBP__SHIFT = 4,
	FMDSI_VIDMODE_CFG__EN_LP_VBP__MASK = 1,
	FMDSI_VIDMODE_CFG__EN_LP_VSA__SHIFT = 3,
	FMDSI_VIDMODE_CFG__EN_LP_VSA__MASK = 1,
	FMDSI_VIDMODE_CFG__VID_MODE_TYPE__SHIFT = 1,
	FMDSI_VIDMODE_CFG__VID_MODE_TYPE__MASK = 3,
	FMDSI_VIDMODE_CFG__EN_VIDEO_MODE__SHIFT = 0,
	FMDSI_VIDMODE_CFG__EN_VIDEO_MODE__MASK = 1,
/* nb above it mutually exclusive with FMDSI_CMD_MODE_CFG__EN_CMD_MODE */

	FMDSI_VID_PKT_CFG__NULL_PKT_SIZE__SHIFT = 21,
	FMDSI_VID_PKT_CFG__NULL_PKT_SIZE__MASK = 0x3ff,
	FMDSI_VID_PKT_CFG__NUM_CHUNKS__SHIFT = 11,
	FMDSI_VID_PKT_CFG__NUM_CHUNKS__MASK = 0x3ff,
	FMDSI_VID_PKT_CFG__VID_PKT_SIZE__SHIFT = 0,
	FMDSI_VID_PKT_CFG__VID_PKT_SIZE__MASK = 0x7ff,

	FMDSI_CMD_MODE_CFG__DCS_LW_TX__SHIFT = 12,
	FMDSI_CMD_MODE_CFG__DCS_LW_TX__MASK = 1,
	FMDSI_CMD_MODE_CFG__GEN_LW_TX__SHIFT = 11,
	FMDSI_CMD_MODE_CFG__GEN_LW_TX__MASK = 1,
	FMDSI_CMD_MODE_CFG__DCS_SW_1P_TX__SHIFT = 8,
	FMDSI_CMD_MODE_CFG__DCS_SW_1P_TX__MASK = 1,
	FMDSI_CMD_MODE_CFG__DCS_SW_0P_TX__SHIFT = 7,
	FMDSI_CMD_MODE_CFG__DCS_SW_0P_TX__MASK = 1,
	FMDSI_CMD_MODE_CFG__GEN_SW_2P_TX__SHIFT = 3,
	FMDSI_CMD_MODE_CFG__GEN_SW_2P_TX__MASK = 1,
	FMDSI_CMD_MODE_CFG__GEN_SW_1P_TX__SHIFT = 2,
	FMDSI_CMD_MODE_CFG__GEN_SW_1P_TX__MASK = 1,
	FMDSI_CMD_MODE_CFG__GEN_SW_0P_TX__SHIFT = 1,
	FMDSI_CMD_MODE_CFG__GEN_SW_0P_TX__MASK = 1,
	FMDSI_CMD_MODE_CFG__EN_CMD_MODE__SHIFT = 0,
	FMDSI_CMD_MODE_CFG__EN_CMD_MODE__MASK = 1,
/* nb above it mutually exclusive with FMDSI_VIDMODE_CFG__EN_VIDEO_MODE */

	FMDSI_TMR_LINE_CFG__HLINE_TIME__SHIFT = 18, /* size of total lines in */
	FMDSI_TMR_LINE_CFG__HLINE_TIME__MASK = 0x3fff, /* in lane byte cycles */
	FMDSI_TMR_LINE_CFG__HBP_TIME__SHIFT = 9, /* horz back porch period */
	FMDSI_TMR_LINE_CFG__HBP_TIME__MASK = 0x1ff, /* in lane byte cycles */
	FMDSI_TMR_LINE_CFG__HSA_TIME__SHIFT = 0, /* HSYNC active period */
	FMDSI_TMR_LINE_CFG__HSA_TIME__MASK = 0x1ff, /* in lane byte cycles */

	FMDSI_VTIMING_CFG__V_ACTIVE_LINES__SHIFT = 16,
	FMDSI_VTIMING_CFG__V_ACTIVE_LINES__MASK = 0x7ff,
	FMDSI_VTIMING_CFG__VFP_LINES__SHIFT = 10,
	FMDSI_VTIMING_CFG__VFP_LINES__MASK = 0x3f,
	FMDSI_VTIMING_CFG__VBP_LINES__SHIFT = 4,
	FMDSI_VTIMING_CFG__VBP_LINES__MASK = 0x3f,
	FMDSI_VTIMING_CFG__VSA_LINES__SHIFT = 0,
	FMDSI_VTIMING_CFG__VSA_LINES__MASK = 0xf,

	FMDSI_PHY_TMR_CFG__PHY_HS2LPTIME__SHIFT = 24,
	FMDSI_PHY_TMR_CFG__PHY_HS2LPTIME__MASK = 0xff,
	FMDSI_PHY_TMR_CFG__PHY_LP2HSTIME__SHIFT = 16,
	FMDSI_PHY_TMR_CFG__PHY_LP2HSTIME__MASK = 0xff,

	FMDSI_GEN_HDR__GEN_WC_MSBYTE__SHIFT = 16,
	FMDSI_GEN_HDR__GEN_WC_MSBYTE__MASK = 0xff,
	FMDSI_GEN_HDR__GEN_WC_LSBYTE__SHIFT = 8,
	FMDSI_GEN_HDR__GEN_WC_LSBYTE__MASK = 0xff,
	FMDSI_GEN_HDR__GEN_VC__SHIFT = 6, /* virtual channel id */
	FMDSI_GEN_HDR__GEN_VC__MASK = 3,
	FMDSI_GEN_HDR__GEN_DT__SHIFT = 0, /* packet type */
	FMDSI_GEN_HDR__GEN_DT__MASK = 0x3f,

	FMDSI_GEN_PLD_DATA__BYTE4__SHIFT = 24,
	FMDSI_GEN_PLD_DATA__BYTE4__MASK = 0xff,
	FMDSI_GEN_PLD_DATA__BYTE3__SHIFT = 16,
	FMDSI_GEN_PLD_DATA__BYTE3__MASK = 0xff,
	FMDSI_GEN_PLD_DATA__BYTE2__SHIFT = 8,
	FMDSI_GEN_PLD_DATA__BYTE2__MASK = 0xff,
	FMDSI_GEN_PLD_DATA__BYTE1__SHIFT = 0,
	FMDSI_GEN_PLD_DATA__BYTE1__MASK = 0xff,

	FMDSI_CMD_PKT_STATUS__WRITE_FULL__SHIFT = 3,
	FMDSI_CMD_PKT_STATUS__WRITE_FULL__MASK = 1,
	FMDSI_CMD_PKT_STATUS__WRITE_EMPTY__SHIFT = 2,
	FMDSI_CMD_PKT_STATUS__WRITE_EMPTY__MASK = 1,
	FMDSI_CMD_PKT_STATUS__CMD_FULL__SHIFT = 1,
	FMDSI_CMD_PKT_STATUS__CMD_FULL__MASK = 1,
	FMDSI_CMD_PKT_STATUS__CMD_EMPTY__SHIFT = 0,
	FMDSI_CMD_PKT_STATUS__CMD_EMPTY__MASK = 1,

	FMDSI_TO_CNT_CFG__HSTX_TO_CNT__SHIFT = 0,
	FMDSI_TO_CNT_CFG__HSTX_TO_CNT__MASK = 0xffff,

	FMDSI_ERROR_ST1__PAYLOAD_SEND__SHIFT = 10,
	FMDSI_ERROR_ST1__PAYLOAD_SEND__MASK = 1,
	FMDSI_ERROR_ST1__PAYLOAD_WRITE__SHIFT = 9,
	FMDSI_ERROR_ST1__PAYLOAD_WRITE__MASK = 1,
	FMDSI_ERROR_ST1__CMD_WRITE__SHIFT = 8,
	FMDSI_ERROR_ST1__CMD_WRITE__MASK = 1,
	FMDSI_ERROR_ST1__DPI_OVERFLOW__SHIFT = 7,
	FMDSI_ERROR_ST1__DPI_OVERFLOW__MASK = 1,
	FMDSI_ERROR_ST1__TIMEOUT_HS_TX__SHIFT = 0,
	FMDSI_ERROR_ST1__TIMEOUT_HS_TX__MASK = 1,

	FMDSI_ERROR_MSK1__PAYLOAD_SEND__SHIFT = 10,
	FMDSI_ERROR_MSK1__PAYLOAD_SEND__MASK = 1,
	FMDSI_ERROR_MSK1__PAYLOAD_WRITE__SHIFT = 9,
	FMDSI_ERROR_MSK1__PAYLOAD_WRITE__MASK = 1,
	FMDSI_ERROR_MSK1__CMD_WRITE__SHIFT = 8,
	FMDSI_ERROR_MSK1__CMD_WRITE__MASK = 1,
	FMDSI_ERROR_MSK1__DPI_OVERFLOW__SHIFT = 7,
	FMDSI_ERROR_MSK1__DPI_OVERFLOW__MASK = 1,
	FMDSI_ERROR_MSK1__TIMEOUT_HS_TX__SHIFT = 0,
	FMDSI_ERROR_MSK1__TIMEOUT_HS_TX__MASK = 1,

	FMDSI_PHY_RSTZ__SHUTDOWNZ__SHIFT = 0,
	FMDSI_PHY_RSTZ__SHUTDOWNZ__MASK = 1,

	FMDSI_PHY_IF_CFG__PHY_STOP_WAIT_TIME__SHIFT = 2,
	FMDSI_PHY_IF_CFG__PHY_STOP_WAIT_TIME__MASK = 0xff,
	FMDSI_PHY_IF_CFG__NUM_LANES__SHIFT = 0,
	FMDSI_PHY_IF_CFG__NUM_LANES__MASK = 3,

	FMDSI_PHY_IF_CTRL__PHY_TX_TRIGGERS__SHIFT = 5,
	FMDSI_PHY_IF_CTRL__PHY_TX_TRIGGERS__MASK = 0xf,
	FMDSI_PHY_IF_CTRL__PHY_TX_DATA_UPLS_EXIT__SHIFT = 4,
	FMDSI_PHY_IF_CTRL__PHY_TX_DATA_UPLS_EXIT__MASK = 1,
	FMDSI_PHY_IF_CTRL__PHY_TX_DATA_UPLS_REQUEST__SHIFT = 3,
	FMDSI_PHY_IF_CTRL__PHY_TX_DATA_UPLS_REQUEST__MASK = 1,
	FMDSI_PHY_IF_CTRL__PHY_TX_CLK_UPLS_EXIT__SHIFT = 2,
	FMDSI_PHY_IF_CTRL__PHY_TX_CLK_UPLS_EXIT__MASK = 1,
	FMDSI_PHY_IF_CTRL__PHY_TX_CLK_UPLS_REQUEST__SHIFT = 1,
	FMDSI_PHY_IF_CTRL__PHY_TX_CLK_UPLS_REQUEST__MASK = 1,
	FMDSI_PHY_IF_CTRL__PHY_TX_REQUEST_PPI_CLK_HS__SHIFT = 0,
	FMDSI_PHY_IF_CTRL__PHY_TX_REQUEST_PPI_CLK_HS__MASK = 1,

	FMDSI_PHY_STATUS__LANE3_UPLS_N__SHIFT = 12,
	FMDSI_PHY_STATUS__LANE3_UPLS_N__MASK = 1,
	FMDSI_PHY_STATUS__LANE3_STOPPED__SHIFT = 11,
	FMDSI_PHY_STATUS__LANE3_STOPPED__MASK = 1,
	FMDSI_PHY_STATUS__LANE2_UPLS_N__SHIFT = 10,
	FMDSI_PHY_STATUS__LANE2_UPLS_N__MASK = 1,
	FMDSI_PHY_STATUS__LANE2_STOPPED__SHIFT = 9,
	FMDSI_PHY_STATUS__LANE2_STOPPED__MASK = 1,
	FMDSI_PHY_STATUS__LANE1_UPLS_N__SHIFT = 8,
	FMDSI_PHY_STATUS__LANE1_UPLS_N__MASK = 1,
	FMDSI_PHY_STATUS__LANE1_STOPPED__SHIFT = 7,
	FMDSI_PHY_STATUS__LANE1_STOPPED__MASK = 1,
	FMDSI_PHY_STATUS__LANE0_UPLS_N__SHIFT = 5,
	FMDSI_PHY_STATUS__LANE0_UPLS_N__MASK = 1,
	FMDSI_PHY_STATUS__LANE0_STOPPED__SHIFT = 4,
	FMDSI_PHY_STATUS__LANE0_STOPPED__MASK = 1,
	FMDSI_PHY_STATUS__CLK_LANE_STOPPED__SHIFT = 2,
	FMDSI_PHY_STATUS__CLK_LANE_STOPPED__MASK = 1,
	FMDSI_PHY_STATUS__DIRECTION__SHIFT = 1,
	FMDSI_PHY_STATUS__DIRECTION__MASK = 1,

	FMDSI_LP_CMD_TIM__OUTVACT_LPCMD_TIME__SHIFT = 8,
	FMDSI_LP_CMD_TIM__OUTVACT_LPCMD_TIME__MASK = 0xff,
	FMDSI_LP_CMD_TIM__INVACT_LPCMD_TIME__SHIFT = 0,
	FMDSI_LP_CMD_TIM__INVACT_LPCMD_TIME__MASK = 0xff,

	FMDSI_PHY_SETUP_CL__SAP_PRE_C__SHIFT = 24,
	FMDSI_PHY_SETUP_CL__SAP_PRE_C__MASK = 0xf,
	FMDSI_PHY_SETUP_CL__SAP_TRAIL_C__SHIFT = 16,
	FMDSI_PHY_SETUP_CL__SAP_TRAIL_C__MASK = 0xf,
	FMDSI_PHY_SETUP_CL__SAP_HS0_C__SHIFT = 8,
	FMDSI_PHY_SETUP_CL__SAP_HS0_C__MASK = 0x3f,
	FMDSI_PHY_SETUP_CL__SAP_TLPX_C__SHIFT = 0,
	FMDSI_PHY_SETUP_CL__SAP_TLPX_C__MASK = 0xf,

	FMDSI_PHY_SETUP_DL__SAP_PRE_D__SHIFT = 24,
	FMDSI_PHY_SETUP_DL__SAP_PRE_D__MASK = 0xf,
	FMDSI_PHY_SETUP_DL__SAP_TRAIL_D__SHIFT = 16,
	FMDSI_PHY_SETUP_DL__SAP_TRAIL_D__MASK = 0xf,
	FMDSI_PHY_SETUP_DL__SAP_HS0_D__SHIFT = 8,
	FMDSI_PHY_SETUP_DL__SAP_HS0_D__MASK = 0x3f,
	FMDSI_PHY_SETUP_DL__SAP_TLPX_D__SHIFT = 0,
	FMDSI_PHY_SETUP_DL__SAP_TLPX_D__MASK = 0xf,
};

#endif

