/*
 * include/video/mb86s70-fb.h
 *
 * Copyright (C) 2013 - 2014 Fujitsu Semiconductor, Ltd
 *
 * Author: Vivien Kuan <vivien.kuan@linaro.org>,
 *	   Andy Green <andy.green@linaro.org>
 */

#ifndef ___LINUX_VIDEO_F_IRIS_H__
#define ___LINUX_VIDEO_F_IRIS_H__

#include <linux/mutex.h>
#include <linux/spinlock.h>
#include <linux/time.h>

#include <video/fdb.h>

#define IRIS_BLITTER_AXIS_LIMIT 8192
#define AXI_BURST_LIMIT 16

/* the scaler Source limit when upscaling or Dest limit when downscaling */
#define IRIS_SCALER_LIMIT 1024

/*
 * temp blitter buffer
 * have to take care of worst of 2 x 1080p in either h or v (dualhead)
 *    4: max bpp
 * cannot tile: whole source must be buffered before any dest writing
 */
#define BLITTER_TEMP_SIZE (1920 * 1080 * 2 * 4)

/* number of pending blitter jobs that may be queued */
#define BLIT_RING_LEN 512

enum ibc_pipe_stages {
	IBCPS_DISABLED,
	IBCPS_F0,
	IBCPS_F1,
	IBCPS_F2,
	IBCPS__RESERVED_4,
	IBCPS_ROP0,
	IBCPS_BITBLEND0,
	IBCPS_CLUT0,
	IBCPS_MATRIX0,
	IBCPS_HSCALER0,
	IBCPS_VSCALER0,
	IBCPS_F4,
	IBCPS_F3,
	IBCPS__RESERVED_D,
	IBCPS_LAYERBLEND0,
	IBCPS_LAYERBLEND1,


};

enum ibc_pipeline_flags {
	IBC_YUV_SOURCE = 1 << 4,
	IBC_F0_INTO_CLUT0_ROP0 = 1 << 5,
	IBC_F1_INTO_ROP0 = 1 << 6,
	IBC_F2_INTO_ROP0 = 1 << 7,
	IBC_ROP_INTO_SCALER = 1 << 8,
	IBC_F0_INTO_STORE0 = 1 << 9,
	IBC_BITBLEND_INTO_STORE0 = 1 << 10,
	IBC_SCALER_INTO_STORE0 = 1 << 11,
	IBC_F2_INTO_BITBLEND_SEC = 1 << 12,
	IBC_MATRIX_INTO_BITBLEND_PRI = 1 << 13,
	IBC_SCALER_INTO_MATRIX = 1 << 14,

	IBC_TYPE_MASK = 0x0f
};

enum blitter_config {
	IRISBC__UNCONFIGURED = 0,
	IRISBC__F0_S0 = 1 | IBC_F0_INTO_STORE0,

	IRISBC__F2_F0_BLITBLEND_S0 = 2 |
		IBC_F0_INTO_CLUT0_ROP0 |
		IBC_ROP_INTO_SCALER |
		IBC_SCALER_INTO_MATRIX |
		IBC_MATRIX_INTO_BITBLEND_PRI |
		IBC_F2_INTO_BITBLEND_SEC |
		IBC_BITBLEND_INTO_STORE0,

	IRISBC__F2_SCALER_S0 = 3 |
		IBC_F2_INTO_ROP0 |
		IBC_ROP_INTO_SCALER |
		IBC_SCALER_INTO_STORE0,

	IRISBC__F2_F0_YUV_S0 = 4 |
		IBC_YUV_SOURCE |
		IBC_F0_INTO_CLUT0_ROP0 |
		IBC_F2_INTO_ROP0 |
		IBC_ROP_INTO_SCALER |
		IBC_SCALER_INTO_MATRIX |
		IBC_MATRIX_INTO_BITBLEND_PRI |
		IBC_BITBLEND_INTO_STORE0,

	IRISBC__F2_F0_F1_YUV_S0 = 5 |
		IBC_YUV_SOURCE |
		IBC_F0_INTO_CLUT0_ROP0 |
		IBC_F1_INTO_ROP0 |
		IBC_F2_INTO_ROP0 |
		IBC_ROP_INTO_SCALER |
		IBC_SCALER_INTO_MATRIX |
		IBC_MATRIX_INTO_BITBLEND_PRI |
		IBC_BITBLEND_INTO_STORE0,
};

struct fdb_blit_entry {
	struct fdb_blit b;
	struct completion *comp;
	struct timespec ts_queued;
	struct fdb_obj_ref *obj;
};

struct fdb_blitter_ring {
	int length; /* how many entries in the ringbuffer */
	volatile int head;
	volatile int tail;
	struct fdb_blit_entry *ring;
	struct list_head blitter_list;
	spinlock_t lock; /* protect changes to the ring */
};

struct blit_completion_ring {
	int length; /* how many entries in the ringbuffer */
	int entry;
	struct blit_completion_id *ring;
};

#if defined(CONFIG_DEBUG_FS)
struct fdb_blitter_stats {
	int count_blitter_ops;
	int count_fill_blits;
	int count_copy_blits;
	int count_scaled_blits;
	u32 count_h_restriction_blits;
	u32 count_v_restriction_blits;
	int count_pipeline_flush;
	u32 count_ms_blitter_busy;
	u32 count_us_pipeline_setup;
	u32 count_ms_in_blitter_wait;
	u32 last_ms_in_blitter_wait;
	u64 count_pixels_blitted;
	u32 count_blitter_overlaps;
	u32 count_blitter_conflicts;
	u32 count_queue_full_events;
	u32 frame_index;
	int worst_ring_depth;
	u32 worst_latency_ms;
	int errors;
};
#endif

struct list_o_completions {
	struct list_head list;
	struct completion c;
};

struct list_o_callback {
	struct list_head list;
	void (*cb)(void *arg);
	void *arg;
	bool retry;
	ktime_t load_time;
};

struct f_iris_par {
	struct f_fdb_child fdb_child;
	struct f_fdb_child *source; /* our owner, eg, drm driver, if any */
	int id;
	int irq[16];
	char irq_name[16][64];
	struct device *dev;
	struct fb_info *info;
	u32 pseudo_palette[16];
	phys_addr_t base_pa;
	void __iomem *base;
	dma_addr_t fbpaddr; /* real start of allocation */
	void *fb_va;
	u32 framesize;
	struct mutex lock; /* serialize api accesses */
	bool simple;
	bool perf_mode;
	int clocks_enabled;
	struct clk *clocks[10];
	int h_pixels_fb_offset;
	int h_bytes_fb_offset;

	dma_addr_t blit_temp_paddr;
	void *blit_temp_va;

	struct list_head list_o_completions;
	u32 frame_index;

	struct completion shadow_display_completion;
	struct completion shadow_memory_completion;
	struct completion dispeng_seq_completion;

	u8 max_burst_buffers;
	u8 max_burst_len_at_max_buffers;
	bool colourbars;

	unsigned int pixel_format; /* fourcc */
	int bits_per_pixel;

	struct fdb_video_timings last_timings;
	bool subsequent;

	spinlock_t spinlock; /* protect blitter sequences */
	enum blitter_config blitter_config;

	struct fdb_blitter_ring *blits;
	volatile bool blitter_busy;
	struct fdb_blit current_job;
	struct work_struct blitter_emergency_work;
	struct timespec ts_entered_state;
	struct list_head blitter_list;
	bool going_away;
	struct completion *current_blit_completion;
	struct work_struct *current_blit_work;

	struct blit_completion_ring *blit_c;
	struct list_head list_o_callback;
	struct list_head list_o_callback_wait;
	struct delayed_work cb_work;
#if defined(CONFIG_DEBUG_FS)
	struct fdb_blitter_stats global;
	struct timespec last;
	struct fdb_blitter_stats since_last;
#endif
};

#define f_par_from_fdb_child(_fc) \
			container_of((_fc), struct f_iris_par, fdb_child)

int f_iris_blit_blocking(struct f_fdb_child *fdb_child, struct fdb_blit *b);
int f_iris_blit_blocking2(struct f_fdb_child *fdb_child, struct fdb_blit *b,
				struct completion *comp_arg, void *obj_in, void *obj_out);
int f_iris_get_blit_comp(struct f_fdb_child *fdb_child,
		struct b_c_id_ring *b_c_id_ring);
void f_iris_blitter_complete_irq(struct f_iris_par *par);
int _f_iris_blitter_poll_queue(struct f_iris_par *par);
void f_iris_blitter_debugfs(struct seq_file *m, struct f_iris_par *par);
void iris_emergency_reset_work(struct work_struct *work);

enum {
	IRIS_GBLC_LOCK_UNLOCK_OFS = 0,
	IRIS_GBLC_LOCK_STATUS_OFS = 4,
	IRIS_GBLC_IPID_OFS = 8,
	IRIS_GBLC_IRQ_ENABLE_OFS = 0x10,
	IRIS_GBLC_IRQ_PRESET_OFS = 0x14,
	IRIS_GBLC_IRQ_CLEAR_OFS = 0x18,
	IRIS_GBLC_IRQ_STATUS_OFS = 0x1c,
};

enum {
	IRIS_GBLC_LOCK_UNLOCK__LOCK_UNLOCK__SHIFT = 0,
	IRIS_GBLC_LOCK_UNLOCK__LOCK_UNLOCK__MASK = 0xffffffff,

	IRIS_GBLC_LOCK_STATUS__LOCKED__SHIFT = 0,
	IRIS_GBLC_LOCK_STATUS__LOCKED__MASK = 1,

	IRIS_GBLC_IPID__DELIVERY_ID__SHIFT = 4,
	IRIS_GBLC_IPID__DELIVERY_ID__MASK = 0xf,

	IRIS_GBLC_IRQ_ENABLE__FRAMEGEN_SHADOW_LOAD__SHIFT = 13,
	IRIS_GBLC_IRQ_ENABLE__FRAMEGEN_SHADOW_LOAD__MASK = 1,
	IRIS_GBLC_IRQ_ENABLE__DISPENG_SEQCOMPLETE__SHIFT = 8,
	IRIS_GBLC_IRQ_ENABLE__DISPENG_SEQCOMPLETE__MASK = 1,
	IRIS_GBLC_IRQ_ENABLE__DISPGEN_SHADOW_LOAD__SHIFT = 7,
	IRIS_GBLC_IRQ_ENABLE__DISPGEN_SHADOW_LOAD__MASK = 1,
	IRIS_GBLC_IRQ_ENABLE__STORE0_FRAMECOMPLETE__SHIFT = 3,
	IRIS_GBLC_IRQ_ENABLE__STORE0_FRAMECOMPLETE__MASK = 1,
	IRIS_GBLC_IRQ_ENABLE__EXTDST0_FRAMECOMPLETE__SHIFT = 4,
	IRIS_GBLC_IRQ_ENABLE__EXTDST0_FRAMECOMPLETE__MASK = 1,
	IRIS_GBLC_IRQ_ENABLE__POS0__SHIFT = 9,
	IRIS_GBLC_IRQ_ENABLE__POS0__MASK = 1,

	IRIS_GBLC_IRQ_CLEAR__FRAMEGEN_SHADOW_LOAD__SHIFT = 13,
	IRIS_GBLC_IRQ_CLEAR__FRAMEGEN_SHADOW_LOAD__MASK = 1,
	IRIS_GBLC_IRQ_CLEAR__DISPENG_SEQCOMPLETE__SHIFT = 8,
	IRIS_GBLC_IRQ_CLEAR__DISPENG_SEQCOMPLETE__MASK = 1,
	IRIS_GBLC_IRQ_CLEAR__DISPGEN_SHADOW_LOAD__SHIFT = 7,
	IRIS_GBLC_IRQ_CLEAR__DISPGEN_SHADOW_LOAD__MASK = 1,
	IRIS_GBLC_IRQ_CLEAR__STORE0_FRAMECOMPLETE__SHIFT = 3,
	IRIS_GBLC_IRQ_CLEAR__STORE0_FRAMECOMPLETE__MASK = 1,
	IRIS_GBLC_IRQ_CLEAR__EXTDST0_FRAMECOMPLETE__SHIFT = 4,
	IRIS_GBLC_IRQ_CLEAR__EXTDST0_FRAMECOMPLETE__MASK = 1,
	IRIS_GBLC_IRQ_CLEAR__POS0__SHIFT = 9,
	IRIS_GBLC_IRQ_CLEAR__POS0__MASK = 1,

	IRIS_GBLC_IRQ_STATUS__FRAMEGEN_SHADOW_LOAD__SHIFT = 13,
	IRIS_GBLC_IRQ_STATUS__FRAMEGEN_SHADOW_LOAD__MASK = 1,
	IRIS_GBLC_IRQ_STATUS__POS0__SHIFT = 9,
	IRIS_GBLC_IRQ_STATUS__POS0__MASK = 1,
	IRIS_GBLC_IRQ_STATUS__DISPENG_SEQCOMPLETE__SHIFT = 8,
	IRIS_GBLC_IRQ_STATUS__DISPENG_SEQCOMPLETE__MASK = 1,
	IRIS_GBLC_IRQ_STATUS__DISPGEN_SHADOW_LOAD__SHIFT = 7,
	IRIS_GBLC_IRQ_STATUS__DISPGEN_SHADOW_LOAD__MASK = 1,
	IRIS_GBLC_IRQ_STATUS__EXTDST0_FRAMECOMPLETE__SHIFT = 4,
	IRIS_GBLC_IRQ_STATUS__EXTDST0_FRAMECOMPLETE__MASK = 1,
	IRIS_GBLC_IRQ_STATUS__STORE0_FRAMECOMPLETE__SHIFT = 3,
	IRIS_GBLC_IRQ_STATUS__STORE0_FRAMECOMPLETE__MASK = 1,
	IRIS_GBLC_IRQ_STATUS__STORE0_SHADOWLOAD__SHIFT = 2,
	IRIS_GBLC_IRQ_STATUS__STORE0_SHADOWLOAD__MASK = 1,
	IRIS_GBLC_IRQ_STATUS__STORE0_SEQCOMPLETE__SHIFT = 0,
	IRIS_GBLC_IRQ_STATUS__STORE0_SEQCOMPLETE__MASK = 1,
};

enum {
	PXE_PXB_FETCH0_CFG_OFS = 0x0800,
	PXE_PXB_FETCH1_CFG_OFS = 0x0804,
	PXE_PXB_FETCH2_CFG_OFS = 0x0808,
	PXE_PXB_STORE0_CFG_OFS = 0x080c,
	PXE_PXB_ROP0_CFG_OFS = 0x0810,
	PXE_PXB_BLITBLEND0_CFG_OFS = 0x0814,
	PXE_PXB_CLUT0_CFG_OFS = 0x0818,
	PXE_PXB_MATRIX0_CFG_OFS = 0x081c,
	PXE_PXB_HSCALER0_CFG_OFS = 0x0820,
	PXE_PXB_VSCALER0_CFG_OFS = 0x0824,
	PXE_PXB_FETCH4_CFG_OFS = 0x0828,
	PXE_PXB_FETCH3_CFG_OFS = 0x082c,
	PXE_PXB_EXTDST0_CFG_OFS = 0x0830,
	PXE_PXB_LYRBLND0_CFG_OFS = 0x0834,
	PXE_PXB_LYRBLND1_CFG_OFS = 0x0838,
	PXE_PXB_RESET_SEQCOMP_OFS = 0x083c,
	PXE_PXB_SYNC_MODE_OFS = 0x0840,
	PXE_PXB_SYNC_TRIGGER_OFS = 0x0848
};

enum {
	PXE_PXB_FETCH0_CFG__FETCH0_SHDW__SHIFT = 26,
	PXE_PXB_FETCH0_CFG__FETCH0_SHDW__MASK = 0x1,

	PXE_PXB_FETCH1_CFG__FETCH1_SHDW__SHIFT = 26,
	PXE_PXB_FETCH1_CFG__FETCH1_SHDW__MASK = 0x1,

	PXE_PXB_FETCH2_CFG__FETCH2_SHDW__SHIFT = 26,
	PXE_PXB_FETCH2_CFG__FETCH2_SHDW__MASK = 0x1,

	PXE_PXB_STORE0_CFG__STORE0_SEL__SHIFT = 27,
	PXE_PXB_STORE0_CFG__STORE0_SEL__MASK = 3,

	PXE_PXB_STORE0_CFG__STORE0_SHDW__SHIFT = 26,
	PXE_PXB_STORE0_CFG__STORE0_SHDW__MASK = 1,

	PXE_PXB_STORE0_CFG__STORE0_SRC_SEL__SHIFT = 0,
	PXE_PXB_STORE0_CFG__STORE0_SRC_SEL__MASK = 0xf,

	PXE_PXB_ROP0_CFG__ROP0_SHDW__SHIFT = 26,
	PXE_PXB_ROP0_CFG__ROP0_SHDW__MASK = 1,
	PXE_PXB_ROP0_CFG__ROP0_CLKEN__SHIFT = 24,
	PXE_PXB_ROP0_CFG__ROP0_CLKEN__MASK = 0x3,
	PXE_PXB_ROP0_CFG__ROP0_TERT_SEL__SHIFT = 16,
	PXE_PXB_ROP0_CFG__ROP0_TERT_SEL__MASK = 0xf,
	PXE_PXB_ROP0_CFG__ROP0_SEC_SEL__SHIFT = 8,
	PXE_PXB_ROP0_CFG__ROP0_SEC_SEL__MASK = 0xf,
	PXE_PXB_ROP0_CFG__ROP0_PRIM_SEL__SHIFT = 0,
	PXE_PXB_ROP0_CFG__ROP0_PRIM_SEL__MASK = 0xf,

	PXE_PXB_BLITBLEND0_CFG__BLITBLEND0_SHDW__SHIFT = 26,
	PXE_PXB_BLITBLEND0_CFG__BLITBLEND0_SHDW__MASK = 0x1,
	PXE_PXB_BLITBLEND0_CFG__BLITBLEND0_CLKEN__SHIFT = 24,
	PXE_PXB_BLITBLEND0_CFG__BLITBLEND0_CLKEN__MASK = 0x3,
	PXE_PXB_BLITBLEND0_CFG__BLITBLEND0_SEC_SEL__SHIFT = 8,
	PXE_PXB_BLITBLEND0_CFG__BLITBLEND0_SEC_SEL__MASK = 0xf,
	PXE_PXB_BLITBLEND0_CFG__BLITBLEND0_PRIM_SEL__SHIFT = 0,
	PXE_PXB_BLITBLEND0_CFG__BLITBLEND0_PRIM_SEL__MASK = 0xf,

	PXE_PXB_CLUT0_CFG__CLUT0_SHDW__SHIFT = 26,
	PXE_PXB_CLUT0_CFG__CLUT0_SHDW__MASK = 0x1,
	PXE_PXB_CLUT0_CFG__CLUT0_SRC_SEL__SHIFT = 0,
	PXE_PXB_CLUT0_CFG__CLUT0_SRC_SEL__MASK = 0xf,

	PXE_PXB_MATRIX0_CFG__MATRIX0_SHDW__SHIFT = 26,
	PXE_PXB_MATRIX0_CFG__MATRIX0_SHDW__MASK = 0x1,
	PXE_PXB_MATRIX0_CFG__MATRIX0_CLKEN__SHIFT = 24,
	PXE_PXB_MATRIX0_CFG__MATRIX0_CLKEN__MASK = 0x3,
	PXE_PXB_MATRIX0_CFG__MATRIX0_SRC_SEL__SHIFT = 0,
	PXE_PXB_MATRIX0_CFG__MATRIX0_SRC_SEL__MASK = 0xf,

	PXE_PXB_HSCALER0_CFG__HSCALER0_SHDW__SHIFT = 26,
	PXE_PXB_HSCALER0_CFG__HSCALER0_SHDW__MASK = 0x1,
	PXE_PXB_HSCALER0_CFG__HSCALER0_CLKEN__SHIFT = 24,
	PXE_PXB_HSCALER0_CFG__HSCALER0_CLKEN__MASK = 0x3,
	PXE_PXB_HSCALER0_CFG__HSCALER0_SRC_SEL__SHIFT = 0,
	PXE_PXB_HSCALER0_CFG__HSCALER0_SRC_SEL__MASK = 0xf,

	PXE_PXB_VSCALER0_CFG__VSCALER0_SHDW__SHIFT = 26,
	PXE_PXB_VSCALER0_CFG__VSCALER0_SHDW__MASK = 0x1,
	PXE_PXB_VSCALER0_CFG__VSCALER0_CLKEN__SHIFT = 24,
	PXE_PXB_VSCALER0_CFG__VSCALER0_CLKEN__MASK = 0x3,
	PXE_PXB_VSCALER0_CFG__VSCALER0_SRC_SEL__SHIFT = 0,
	PXE_PXB_VSCALER0_CFG__VSCALER0_SRC_SEL__MASK = 0xf,

	PXE_PXB_FETCH4_CFG__FETCH4_SHDW__SHIFT = 26,
	PXE_PXB_FETCH4_CFG__FETCH4_SHDW__MASK = 0x1,

	PXE_PXB_FETCH3_CFG__FETCH3_SHDW__SHIFT = 26,
	PXE_PXB_FETCH3_CFG__FETCH3_SHDW__MASK = 0x1,
	PXE_PXB_FETCH3_CFG__FETCH3_SRC_SEL__SHIFT = 0,
	PXE_PXB_FETCH3_CFG__FETCH3_SRC_SEL__MASK = 0xf,

	PXE_PXB_EXTDST0_CFG__EXTDST0_SHDW__SHIFT = 26,
	PXE_PXB_EXTDST0_CFG__EXTDST0_SHDW__MASK = 0x1,
	PXE_PXB_EXTDST0_CFG__EXTDST0_SRC_SEL__SHIFT = 0,
	PXE_PXB_EXTDST0_CFG__EXTDST0_SRC_SEL__MASK = 0xf,

	PXE_PXB_LYRBLND0_CFG__LYRBLND0_SHDW__SHIFT = 26,
	PXE_PXB_LYRBLND0_CFG__LYRBLND0_SHDW__MASK = 0x1,
	PXE_PXB_LYRBLND0_CFG__LYRBLND0_CLKEN__SHIFT = 24,
	PXE_PXB_LYRBLND0_CFG__LYRBLND0_CLKEN__MASK = 0x3,
	PXE_PXB_LYRBLND0_CFG__LYRBLND0_SEC_SEL__SHIFT = 8,
	PXE_PXB_LYRBLND0_CFG__LYRBLND0_SEC_SEL__MASK = 0xf,
	PXE_PXB_LYRBLND0_CFG__LYRBLND0_PRIM_SEL__SHIFT = 0,
	PXE_PXB_LYRBLND0_CFG__LYRBLND0_PRIM_SEL__MASK = 0xf,

	PXE_PXB_LYRBLND1_CFG__LYRBLND1_SHDW__SHIFT = 26,
	PXE_PXB_LYRBLND1_CFG__LYRBLND1_SHDW__MASK = 0x1,
	PXE_PXB_LYRBLND1_CFG__LYRBLND1_CLKEN__SHIFT = 24,
	PXE_PXB_LYRBLND1_CFG__LYRBLND1_CLKEN__MASK = 0x3,
	PXE_PXB_LYRBLND1_CFG__LYRBLND1_SEC_SEL__SHIFT = 8,
	PXE_PXB_LYRBLND1_CFG__LYRBLND1_SEC_SEL__MASK = 0xf,
	PXE_PXB_LYRBLND1_CFG__LYRBLND1_PRIM_SEL__SHIFT = 0,
	PXE_PXB_LYRBLND1_CFG__LYRBLND1_PRIM_SEL__MASK = 0xf,

	PXE_PXB_RESET_SEQCOMP__EXDST0_TRIG_SEQCOMP__SHIFT = 4,
	PXE_PXB_RESET_SEQCOMP__EXDST0_TRIG_SEQCOMP__MASK = 1,
	PXE_PXB_RESET_SEQCOMP__STORE0_TRIG_SEQCOMP__SHIFT = 0,
	PXE_PXB_RESET_SEQCOMP__STORE0_TRIG_SEQCOMP__MASK = 1,

	PXE_PXB_SYNC_MODE__STORE0_SYNC_MODE__SHIFT = 0,
	PXE_PXB_SYNC_MODE__STORE0_SYNC_MODE__MASK = 0x3,

	PXE_PXB_SYNC_MODE__STORE0_SWRESET__SHIFT = 3,
	PXE_PXB_SYNC_MODE__STORE0_SWRESET__MASK = 1,

	PXE_PXB_SYNC_MODE__EXTDST0_SYNC_MODE__SHIFT = 4,
	PXE_PXB_SYNC_MODE__EXTDST0_SYNC_MODE__MASK = 0x3,

	PXE_PXB_SYNC_MODE__EXTDST0_SWRESET__SHIFT = 7,
	PXE_PXB_SYNC_MODE__EXTDST0_SWRESET__MASK = 1,

	PXE_PXB_SYNC_TRIGGER__EXTDST0_SYNC_TRIGGER__SHIFT = 4,
	PXE_PXB_SYNC_TRIGGER__EXTDST0_SYNC_TRIGGER__MASK = 0x1,
	PXE_PXB_SYNC_TRIGGER__STORE0_SYNC_TRIGGER__SHIFT = 0,
	PXE_PXB_SYNC_TRIGGER__STORE0_SYNC_TRIGGER__MASK = 0x1
};

enum {
	PXENG_DISPCFG_POLARITY_CTRL_OFS = 0x5000,
	PXENG_DISPCFG_SIG_SRC_SELECT_OFS = 0x5004,
	PXENG_DISPCFG_SIG_PANIC_COLOUR_OFS = 0x5008,

	PXENG_DISPCFG_POLARITY_CTRL__POLHS__SHIFT = 0,
	PXENG_DISPCFG_POLARITY_CTRL__POLHS__MASK = 1,
	PXENG_DISPCFG_POLARITY_CTRL__POLVS__SHIFT = 1,
	PXENG_DISPCFG_POLARITY_CTRL__POLVS__MASK = 1,
	PXENG_DISPCFG_POLARITY_CTRL__POLEN__SHIFT = 2,
	PXENG_DISPCFG_POLARITY_CTRL__POLEN__MASK = 1,
	PXENG_DISPCFG_POLARITY_CTRL__PIXINV__SHIFT = 3,
	PXENG_DISPCFG_POLARITY_CTRL__PIXINV__MASK = 1,
};

enum {
	PXE_F0_STATCTL_OFS = 0x0c00,
	PXE_F0_BRSTBUFMGT_OFS = 0x0c04,
	PXE_F0_BASEADDRESS_OFS = 0x0c08,
	PXE_F0_SRCBUFSTRIDE_OFS = 0x0c0c,
	PXE_F0_SRCBUFATTRIBUTES_OFS = 0x0c10,
	PXE_F0_FRAMEXOFS_OFS = 0x0c18,
	PXE_F0_FRAMEYOFS_OFS = 0x0c1c,
	PXE_F0_FRAMEDIM_OFS = 0x0c20,
	PXE_F0_DELTAXX_OFS = 0x0c24,
	PXE_F0_DELTAYY_OFS = 0x0c28,
	PXE_F0_COLCOMPBITS_OFS = 0x0c34,
	PXE_F0_COLCOMPSHIFT_OFS = 0x0c38,
	PXE_F0_CONSTANT_COLOR_OFS = 0x0c3c,
	PXE_F0_CTL_OFS = 0x0c44,
	PXE_F0_CTLTRIG_OFS = 0x0c48,
	PXE_F0_BURSTPROPS_OFS = 0x0c54,
};

enum {
	PXE_F0_STATCTL__CLOCKDISABLE__SHIFT = 5,
	PXE_F0_STATCTL__CLOCKDISABLE__MASK = 0x1,
	PXE_F0_STATCTL__SWRESET__SHIFT = 4,
	PXE_F0_STATCTL__SWRESET__MASK = 0x1,
	PXE_F0_STATCTL__SHDEN__SHIFT = 0,
	PXE_F0_STATCTL__SHDEN__MASK = 0x1,

	PXE_F0_BRSTBUFMGT__SETBURSTLENGTH__SHIFT = 8,
	PXE_F0_BRSTBUFMGT__SETBURSTLENGTH__MASK = 0x1f,
	PXE_F0_BRSTBUFMGT__SETNUMBUFFERS__SHIFT = 0,
	PXE_F0_BRSTBUFMGT__SETNUMBUFFERS__MASK = 0xff,

	PXE_F0_SRCBUFSTRIDE__STRIDE__SHIFT = 0,
	PXE_F0_SRCBUFSTRIDE__STRIDE__MASK = 0xffff,

	PXE_F0_SRCBUFATTRIBUTES__LINECOUNT__SHIFT = 16,
	PXE_F0_SRCBUFATTRIBUTES__LINECOUNT__MASK = 0x3fff,
	PXE_F0_SRCBUFATTRIBUTES__LINEWIDTH__SHIFT = 0,
	PXE_F0_SRCBUFATTRIBUTES__LINEWIDTH__MASK = 0x3fff,

	PXE_F0_FRAMEXOFS__XOFS_FP2__SHIFT = 14,
	PXE_F0_FRAMEXOFS__XOFS_FP2__MASK = 0x3ffff,

	PXE_F0_FRAMEYOFS__YOFS_FP2__SHIFT = 14,
	PXE_F0_FRAMEYOFS__YOFS_FP2__MASK = 0x3ffff,

	PXE_F0_FRAMEDIM__FRAMEHEIGHT__SHIFT = 16,
	PXE_F0_FRAMEDIM__FRAMEHEIGHT__MASK = 0x3fff,
	PXE_F0_FRAMEDIM__FRAMEWIDTH__SHIFT = 0,
	PXE_F0_FRAMEDIM__FRAMEWIDTH__MASK = 0x3fff,

	PXE_F0_DELTAXX__DELTAX__SHIFT = 16,
	PXE_F0_DELTAXX__DELTAX__MASK = 0x3f,

	PXE_F0_DELTAYY__DELTAY__SHIFT = 16,
	PXE_F0_DELTAYY__DELTAY__MASK = 0x3f,

	PXE_F0_COLCOMPBITS__BITSRED__SHIFT = 24,
	PXE_F0_COLCOMPBITS__BITSRED__MASK = 0xf,
	PXE_F0_COLCOMPBITS__BITSGREEN__SHIFT = 16,
	PXE_F0_COLCOMPBITS__BITSGREEN__MASK = 0xf,
	PXE_F0_COLCOMPBITS__BITSBLUE__SHIFT = 8,
	PXE_F0_COLCOMPBITS__BITSBLUE__MASK = 0xf,
	PXE_F0_COLCOMPBITS__BITSALPHA__SHIFT = 0,
	PXE_F0_COLCOMPBITS__BITSALPHA__MASK = 0xf,

	PXE_F0_COLCOMPSHIFT__SHIFTRED__SHIFT = 24,
	PXE_F0_COLCOMPSHIFT__SHIFTRED__MASK = 0x1f,
	PXE_F0_COLCOMPSHIFT__SHIFTGREEN__SHIFT = 16,
	PXE_F0_COLCOMPSHIFT__SHIFTGREEN__MASK = 0x1f,
	PXE_F0_COLCOMPSHIFT__SHIFTBLUE__SHIFT = 8,
	PXE_F0_COLCOMPSHIFT__SHIFTBLUE__MASK = 0x1f,
	PXE_F0_COLCOMPSHIFT__SHIFTALPHA__SHIFT = 0,
	PXE_F0_COLCOMPSHIFT__SHIFTALPHA__MASK = 0x1f,

	PXE_F0_CONSTANT_COLOR__RED__SHIFT = 24,
	PXE_F0_CONSTANT_COLOR__RED__MASK = 0xff,
	PXE_F0_CONSTANT_COLOR__GREEN__SHIFT = 16,
	PXE_F0_CONSTANT_COLOR__GREEN__MASK = 0xff,
	PXE_F0_CONSTANT_COLOR__BLUE__SHIFT = 8,
	PXE_F0_CONSTANT_COLOR__BLUE__MASK = 0xff,
	PXE_F0_CONSTANT_COLOR__ALPHA__SHIFT = 0,
	PXE_F0_CONSTANT_COLOR__ALPHA__MASK = 0xff,

	PXE_F0_CTL__BITSPERPIXEL__SHIFT = 0,
	PXE_F0_CTL__BITSPERPIXEL__MASK = 0x3f,
	PXE_F0_CTL__ALPHA_MULTIPLY__SHIFT = 8,
	PXE_F0_CTL__ALPHA_MULTIPLY__MASK = 1,
	PXE_F0_CTL__TILEMODE__SHIFT = 12,
	PXE_F0_CTL__TILEMODE__MASK = 0x3,

	PXE_F0_CTLTRIG__SHDTOKGEN__SHIFT = 0,
	PXE_F0_CTLTRIG__SHDTOKGEN__MASK = 0x1,

	PXE_F0_BURSTPROPS__MAXBURSTLENGTH__SHIFT = 8,
	PXE_F0_BURSTPROPS__MAXBURSTLENGTH__MASK = 0x1f,
	PXE_F0_BURSTPROPS__MAXNUMBUFFERS__SHIFT = 0,
	PXE_F0_BURSTPROPS__MAXNUMBUFFERS__MASK = 0xff,
};

enum {
	PXE_F1_STATCTL_OFS = 0x1000,
	PXE_F1_BRSTBUFMGT_OFS = 0x1004,
	PXE_F1_BASEADDRESS_OFS = 0x1008,
	PXE_F1_SRCBUFSTRIDE_OFS = 0x100c,
	PXE_F1_SRCBUFATTR_OFS = 0x1010,
	PXE_F1_FRAMEDIM_OFS = 0x101c,
	PXE_F1_DELTAXX_OFS = 0x1020,
	PXE_F1_DELTAYY_OFS = 0x1024,
	PXE_F1_COLCOMPBITS_OFS = 0x1030,
	PXE_F1_COLCOMPSHIFT_OFS = 0x1034,
	PXE_F1_CTL_OFS = 0x1040,
	PXE_F1_CTLTRIG_OFS = 0x1044,
	PXE_F1_BURSTPROPS_OFS = 0x1050,
};

enum {
	PXE_F1_STATCTL__CLOCKDISABLE__SHIFT = 5,
	PXE_F1_STATCTL__CLOCKDISABLE__MASK = 0x1,
	PXE_F1_STATCTL__SWRESET__SHIFT = 4,
	PXE_F1_STATCTL__SWRESET__MASK = 0x1,
	PXE_F1_STATCTL__SHDEN__SHIFT = 0,
	PXE_F1_STATCTL__SHDEN__MASK = 0x1,

	PXE_F1_BRSTBUFMGT__SETBURSTLENGTH__SHIFT = 8,
	PXE_F1_BRSTBUFMGT__SETBURSTLENGTH__MASK = 0x1f,
	PXE_F1_BRSTBUFMGT__SETNUMBUFFERS__SHIFT = 0,
	PXE_F1_BRSTBUFMGT__SETNUMBUFFERS__MASK = 0xff,

	PXE_F1_SRCBUFSTRIDE__STRIDE__SHIFT = 0,
	PXE_F1_SRCBUFSTRIDE__STRIDE__MASK = 0xffff,

	PXE_F1_SRCBUFATTR__LINECOUNT__SHIFT = 16,
	PXE_F1_SRCBUFATTR__LINECOUNT__MASK = 0x3fff,
	PXE_F1_SRCBUFATTR__LINEWIDTH__SHIFT = 0,
	PXE_F1_SRCBUFATTR__LINEWIDTH__MASK = 0x3fff,

	PXE_F1_FRAMEDIM__FRAMEHEIGHT__SHIFT = 16,
	PXE_F1_FRAMEDIM__FRAMEHEIGHT__MASK = 0x3fff,
	PXE_F1_FRAMEDIM__FRAMEWIDTH__SHIFT = 0,
	PXE_F1_FRAMEDIM__FRAMEWIDTH__MASK = 0x3fff,

	PXE_F1_DELTAXX__DELTAX__SHIFT = 16,
	PXE_F1_DELTAXX__DELTAX__MASK = 0x3f,

	PXE_F1_DELTAYY__DELTAY__SHIFT = 16,
	PXE_F1_DELTAYY__DELTAY__MASK = 0x3f,

	PXE_F1_COLCOMPBITS__BITSRED__SHIFT = 24,
	PXE_F1_COLCOMPBITS__BITSRED__MASK = 0xf,
	PXE_F1_COLCOMPBITS__BITSGREEN__SHIFT = 16,
	PXE_F1_COLCOMPBITS__BITSGREEN__MASK = 0xf,
	PXE_F1_COLCOMPBITS__BITSBLUE__SHIFT = 8,
	PXE_F1_COLCOMPBITS__BITSBLUE__MASK = 0xf,
	PXE_F1_COLCOMPBITS__BITSALPHA__SHIFT = 0,
	PXE_F1_COLCOMPBITS__BITSALPHA__MASK = 0xf,

	PXE_F1_COLCOMPSHIFT__SHIFTRED__SHIFT = 24,
	PXE_F1_COLCOMPSHIFT__SHIFTRED__MASK = 0xf,
	PXE_F1_COLCOMPSHIFT__SHIFTGREEN__SHIFT = 16,
	PXE_F1_COLCOMPSHIFT__SHIFTGREEN__MASK = 0xf,
	PXE_F1_COLCOMPSHIFT__SHIFTBLUE__SHIFT = 8,
	PXE_F1_COLCOMPSHIFT__SHIFTBLUE__MASK = 0xf,
	PXE_F1_COLCOMPSHIFT__SHIFTALPHA__SHIFT = 0,
	PXE_F1_COLCOMPSHIFT__SHIFTALPHA__MASK = 0xf,

	PXE_F1_CTL__BITSPERPIXEL__SHIFT = 0,
	PXE_F1_CTL__BITSPERPIXEL__MASK = 0x3f,
	PXE_F1_CTRL__ALPHA_MULTIPLY__SHIFT = 8,
	PXE_F1_CTRL__ALPHA_MULTIPLY__MASK = 1,
	PXE_F1_CTRL__TILEMODE__SHIFT = 12,
	PXE_F1_CTRL__TILEMODE__MASK = 0x3,

	PXE_F1_CTLTRIG__SHDTOKGEN__SHIFT = 0,
	PXE_F1_CTLTRIG__SHDTOKGEN__MASK = 0x1,

	PXE_F1_BURSTPROPS__MAXBURSTLENGTH__SHIFT = 8,
	PXE_F1_BURSTPROPS__MAXBURSTLENGTH__MASK = 0x1f,
	PXE_F1_BURSTPROPS__MAXNUMBUFFERS__SHIFT = 0,
	PXE_F1_BURSTPROPS__MAXNUMBUFFERS__MASK = 0xff,
};

enum {
	PXE_F2_STATCTL_OFS = 0x1400,
	PXE_F2_BRSTBUFMGT_OFS = 0x1404,
	PXE_F2_BASEADDRESS_OFS = 0x1408,
	PXE_F2_SRCBUFSTRIDE_OFS = 0x140c,
	PXE_F2_SRCBUFATTR_OFS = 0x1410,
	PXE_F2_FRAMEXOFFSET_OFS = 0x1414,
	PXE_F2_FRAMEYOFFSET_OFS = 0x1418,
	PXE_F2_FRAMEDIM_OFS = 0x141c,
	PXE_F2_DELTAXX_OFS = 0x1420,
	PXE_F2_DELTAXY_OFS = 0x1424,
	PXE_F2_DELTAYX_OFS = 0x1428,
	PXE_F2_DELTAYY_OFS = 0x142c,
	PXE_F2_COLCOMPBITS_OFS = 0x1438,
	PXE_F2_COLCOMPSHIFT_OFS = 0x143c,
	PXE_F2_CTL_OFS = 0x1450,
	PXE_F2_CTLTRIG_OFS = 0x1454,
	PXE_F2_BURSTPROPS_OFS = 0x1460,
};

enum {
	PXE_F2_STATCTL__CLOCKDISABLE__SHIFT = 5,
	PXE_F2_STATCTL__CLOCKDISABLE__MASK = 0x1,
	PXE_F2_STATCTL__SWRESET__SHIFT = 4,
	PXE_F2_STATCTL__SWRESET__MASK = 0x1,
	PXE_F2_STATCTL__SHDEN__SHIFT = 0,
	PXE_F2_STATCTL__SHDEN__MASK = 0x1,

	PXE_F2_BRSTBUFMGT__SETBURSTLENGTH__SHIFT = 8,
	PXE_F2_BRSTBUFMGT__SETBURSTLENGTH__MASK = 0x1f,
	PXE_F2_BRSTBUFMGT__SETNUMBUFFERS__SHIFT = 0,
	PXE_F2_BRSTBUFMGT__SETNUMBUFFERS__MASK = 0xff,

	PXE_F2_SRCBUFSTRIDE__STRIDE__SHIFT = 0,
	PXE_F2_SRCBUFSTRIDE__STRIDE__MASK = 0xffff,

	PXE_F2_SRCBUFATTR__LINECOUNT__SHIFT = 16,
	PXE_F2_SRCBUFATTR__LINECOUNT__MASK = 0x3fff,
	PXE_F2_SRCBUFATTR__LINEWIDTH__SHIFT = 0,
	PXE_F2_SRCBUFATTR__LINEWIDTH__MASK = 0x3fff,

	PXE_F2_FRAMEDIM__FRAMEHEIGHT__SHIFT = 16,
	PXE_F2_FRAMEDIM__FRAMEHEIGHT__MASK = 0x3fff,
	PXE_F2_FRAMEDIM__FRAMEWIDTH__SHIFT = 0,
	PXE_F2_FRAMEDIM__FRAMEWIDTH__MASK = 0x3fff,

	PXE_F2_DELTAXX__DELTAXX__SHIFT = 0,
	PXE_F2_DELTAXX__DELTAXX__MASK = 0x1ffffff,

	PXE_F2_DELTAXY__DELTAXY__SHIFT = 0,
	PXE_F2_DELTAXY__DELTAXY__MASK = 0x1ffffff,

	PXE_F2_DELTAYX__DELTAYX__SHIFT = 0,
	PXE_F2_DELTAYX__DELTAYX__MASK = 0x1ffffff,

	PXE_F2_DELTAYY__DELTAYY__SHIFT = 0,
	PXE_F2_DELTAYY__DELTAYY__MASK = 0x1ffffff,

	PXE_F2_COLCOMPBITS__BITSRED__SHIFT = 24,
	PXE_F2_COLCOMPBITS__BITSRED__MASK = 0xf,
	PXE_F2_COLCOMPBITS__BITSGREEN__SHIFT = 16,
	PXE_F2_COLCOMPBITS__BITSGREEN__MASK = 0xf,
	PXE_F2_COLCOMPBITS__BITSBLUE__SHIFT = 8,
	PXE_F2_COLCOMPBITS__BITSBLUE__MASK = 0xf,
	PXE_F2_COLCOMPBITS__BITSALPHA__SHIFT = 0,
	PXE_F2_COLCOMPBITS__BITSALPHA__MASK = 0xf,

	PXE_F2_COLCOMPSHIFT__SHIFTRED__SHIFT = 24,
	PXE_F2_COLCOMPSHIFT__SHIFTRED__MASK = 0x1f,
	PXE_F2_COLCOMPSHIFT__SHIFTGREEN__SHIFT = 16,
	PXE_F2_COLCOMPSHIFT__SHIFTGREEN__MASK = 0x1f,
	PXE_F2_COLCOMPSHIFT__SHIFTBLUE__SHIFT = 8,
	PXE_F2_COLCOMPSHIFT__SHIFTBLUE__MASK = 0x1f,
	PXE_F2_COLCOMPSHIFT__SHIFTALPHA__SHIFT = 0,
	PXE_F2_COLCOMPSHIFT__SHIFTALPHA__MASK = 0x1f,

	PXE_F2_CTL__FILTERMODE__SHIFT = 20,
	PXE_F2_CTL__FILTERMODE__MASK = 0x3f,
	PXE_F2_CTL__BITSPERPIXEL__SHIFT = 0,
	PXE_F2_CTL__BITSPERPIXEL__MASK = 0x3f,
	PXE_F2_CTL__ALPHA_MULTIPLY__SHIFT = 8,
	PXE_F2_CTL__ALPHA_MULTIPLY__MASK = 1,
	PXE_F2_CTL__TILEMODE__SHIFT = 12,
	PXE_F2_CTL__TILEMODE__MASK = 0x3,

	PXE_F2_CTLTRIG__SHDTOKGEN__SHIFT = 0,
	PXE_F2_CTLTRIG__SHDTOKGEN__MASK = 0x1,

	PXE_F2_BURSTPROPS__MAXBURSTLENGTH__SHIFT = 8,
	PXE_F2_BURSTPROPS__MAXBURSTLENGTH__MASK = 0x1f,
	PXE_F2_BURSTPROPS__MAXNUMBUFFERS__SHIFT = 0,
	PXE_F2_BURSTPROPS__MAXNUMBUFFERS__MASK = 0xff,
};

enum {
	PXE_S0_STATCTL_OFS = 0x1800,
	PXE_S0_BURSTBUFFER_MGT_OFS = 0x1808,
	PXE_S0_BASEADDRESS_OFS = 0x1808,
	PXE_S0_DESTBUFSTRIDE_OFS = 0x180c,
	PXE_S0_COLCOMPBITS_OFS = 0x1818,
	PXE_S0_COLCOMPSHIFT_OFS = 0x181c,
	PXE_S0_CTL_OFS = 0x1820,
	PXE_S0_START_OFS = 0x1824,
	PXE_S0_STATUS_OFS = 0x1834,
};

enum {
	PXE_S0_STATCTL__CLOCKDISABLE__SHIFT = 5,
	PXE_S0_STATCTL__CLOCKDISABLE__MASK = 0x1,
	PXE_S0_STATCTL__SWRESET__SHIFT = 4,
	PXE_S0_STATCTL__SWRESET__MASK = 0x1,
	PXE_S0_STATCTL__SHDEN__SHIFT = 0,
	PXE_S0_STATCTL__SHDEN__MASK = 0x1,

	PXE_S0_BURSTBUFFER_MGT__LENGTH__SHIFT = 8,
	PXE_S0_BURSTBUFFER_MGT__LENGTH__MASK = 0xf,

	PXE_S0_DESTBUFSTRIDE__STRIDE__SHIFT = 0,
	PXE_S0_DESTBUFSTRIDE__STRIDE__MASK = 0xffff,

	PXE_S0_COLCOMPBITS__BITSRED__SHIFT = 24,
	PXE_S0_COLCOMPBITS__BITSRED__MASK = 0xf,
	PXE_S0_COLCOMPBITS__BITSGREEN__SHIFT = 16,
	PXE_S0_COLCOMPBITS__BITSGREEN__MASK = 0xf,
	PXE_S0_COLCOMPBITS__BITSBLUE__SHIFT = 8,
	PXE_S0_COLCOMPBITS__BITSBLUE__MASK = 0xf,
	PXE_S0_COLCOMPBITS__BITSALPHA__SHIFT = 0,
	PXE_S0_COLCOMPBITS__BITSALPHA__MASK = 0xf,

	PXE_S0_COLCOMPSHIFT__SHIFTRED__SHIFT = 24,
	PXE_S0_COLCOMPSHIFT__SHIFTRED__MASK = 0x1f,
	PXE_S0_COLCOMPSHIFT__SHIFTGREEN__SHIFT = 16,
	PXE_S0_COLCOMPSHIFT__SHIFTGREEN__MASK = 0x1f,
	PXE_S0_COLCOMPSHIFT__SHIFTBLUE__SHIFT = 8,
	PXE_S0_COLCOMPSHIFT__SHIFTBLUE__MASK = 0x1f,
	PXE_S0_COLCOMPSHIFT__SHIFTALPHA__SHIFT = 0,
	PXE_S0_COLCOMPSHIFT__SHIFTALPHA__MASK = 0x1f,

	PXE_S0_CTL__BITSPERPIXEL__SHIFT = 0,
	PXE_S0_CTL__BITSPERPIXEL__MASK = 0x7f,

	PXE_S0_START__START__SHIFT = 0,
	PXE_S0_START__START__MASK = 0x1,
};

enum {
	PXENG_ROP0_STATCTL_OFS = 0x1c00,
	PXENG_ROP0_CTL_OFS = 0x1c04,
};

enum {
	PXENG_ROP0_STATCTL__SHDEN__SHIFT = 0,
	PXENG_ROP0_STATCTL__SHDEN__MASK = 0x1,

	PXENG_ROP0_CTL__TERTDIV2__SHIFT = 10,
	PXENG_ROP0_CTL__TERTDIV2__MASK = 0x1,
	PXENG_ROP0_CTL__SECDIV2__SHIFT = 9,
	PXENG_ROP0_CTL__SECDIV2__MASK = 0x1,
	PXENG_ROP0_CTL__PRIMDIV2__SHIFT = 8,
	PXENG_ROP0_CTL__PRIMDIV2__MASK = 0x1,
	PXENG_ROP0_CTL__REDMODE__SHIFT = 7,
	PXENG_ROP0_CTL__REDMODE__MASK = 0x1,
	PXENG_ROP0_CTL__GREENMODE__SHIFT = 6,
	PXENG_ROP0_CTL__GREENMODE__MASK = 0x1,
	PXENG_ROP0_CTL__BLUEMODE__SHIFT = 5,
	PXENG_ROP0_CTL__BLUEMODE__MASK = 0x1,
	PXENG_ROP0_CTL__ALPHAMODE__SHIFT = 4,
	PXENG_ROP0_CTL__ALPHAMODE__MASK = 0x1,
	PXENG_ROP0_CTL__MODE__SHIFT = 0,
	PXENG_ROP0_CTL__MODE__MASK = 0x1,
};

enum {
	PXENG_BLITBLEND0_STATCTL_OFS = 0x2000,
	PXENG_BLITBLEND0_CTL_OFS = 0x2004,
	PXENG_BLITBLEND0_CONSTANTCOL_OFS = 0x2008,
	PXENG_BLITBLEND0_COLREDBLEND_OFS = 0x200C,
	PXENG_BLITBLEND0_COLGREENBLEND_OFS = 0x2010,
	PXENG_BLITBLEND0_COLBLUEBLEND_OFS = 0x2014,
	PXENG_BLITBLEND0_ALPHABLEND_OFS = 0x2018,
	PXENG_BLITBLEND0_MODE1_OFS = 0x201c,
	PXENG_BLITBLEND0_MODE2_OFS = 0x2020,
};

enum {
	PXENG_BLITBLEND0_STATCTL__SHDEN__SHIFT = 0,
	PXENG_BLITBLEND0_STATCTL__SHDEN__MASK = 0x1,

	PXENG_BLITBLEND0_CTL__MODE__SHIFT = 0,
	PXENG_BLITBLEND0_CTL__MODE__MASK = 1,

	PXENG_BLITBLEND0_CONSTANTCOL__RED__SHIFT = 24,
	PXENG_BLITBLEND0_CONSTANTCOL__RED__MASK = 0xff,
	PXENG_BLITBLEND0_CONSTANTCOL__GREEN__SHIFT = 16,
	PXENG_BLITBLEND0_CONSTANTCOL__GREEN__MASK = 0xff,
	PXENG_BLITBLEND0_CONSTANTCOL__BLUE__SHIFT = 8,
	PXENG_BLITBLEND0_CONSTANTCOL__BLUE__MASK = 0xff,
	PXENG_BLITBLEND0_CONSTANTCOL__ALPHA__SHIFT = 0,
	PXENG_BLITBLEND0_CONSTANTCOL__ALPHA__MASK = 0xff,

	PXENG_BLITBLEND0_COLREDBLEND__DST__SHIFT = 16,
	PXENG_BLITBLEND0_COLREDBLEND__DST__MASK = 0xffff,
	PXENG_BLITBLEND0_COLREDBLEND__SRC__SHIFT = 0,
	PXENG_BLITBLEND0_COLREDBLEND__SRC__MASK = 0xffff,

	PXENG_BLITBLEND0_COLGREENBLEND__DST__SHIFT = 16,
	PXENG_BLITBLEND0_COLGREENBLEND__DST__MASK = 0xffff,
	PXENG_BLITBLEND0_COLGREENBLEND__SRC__SHIFT = 0,
	PXENG_BLITBLEND0_COLGREENBLEND__SRC__MASK = 0xffff,

	PXENG_BLITBLEND0_COLBLUEBLEND__DST__SHIFT = 16,
	PXENG_BLITBLEND0_COLBLUEBLEND__DST__MASK = 0xffff,
	PXENG_BLITBLEND0_COLBLUEBLEND__SRC__SHIFT = 0,
	PXENG_BLITBLEND0_COLBLUEBLEND__SRC__MASK = 0xffff,

	PXENG_BLITBLEND0_ALPHABLEND__DST__SHIFT = 16,
	PXENG_BLITBLEND0_ALPHABLEND__DST__MASK = 0xffff,
	PXENG_BLITBLEND0_ALPHABLEND__SRC__SHIFT = 0,
	PXENG_BLITBLEND0_ALPHABLEND__SRC__MASK = 0xffff,

	PXENG_BLITBLEND0_MODE1__GREEN__SHIFT = 16,
	PXENG_BLITBLEND0_MODE1__GREEN__MASK = 0xffff,
	PXENG_BLITBLEND0_MODE1__RED__SHIFT = 0,
	PXENG_BLITBLEND0_MODE1__RED__MASK = 0xffff,

	PXENG_BLITBLEND0_MODE2__ALPHA__SHIFT = 16,
	PXENG_BLITBLEND0_MODE2__ALPHA__MASK = 0xffff,
	PXENG_BLITBLEND0_MODE2__BLUE__SHIFT = 0,
	PXENG_BLITBLEND0_MODE2__BLUE__MASK = 0xffff,
};

enum {
	PXENG_CLUT0_STATCTL_OFS = 0x2400,
	PXENG_CLUT0_UNSHADOWEDCONTROL_OFS = 0x2404,
	PXENG_CLUT0_CTRL_OFS = 0x2408
};

enum {
	PXENG_CLUT0_STATCTL__SHDEN__SHIFT = 0,
	PXENG_CLUT0_STATCTL__SHDEN__MASK = 0x1,

	PXENG_CLUT0_UNSHADOWEDCONTROL__R_EN__SHIFT = 2,
	PXENG_CLUT0_UNSHADOWEDCONTROL__R_EN__MASK = 0x1,
	PXENG_CLUT0_UNSHADOWEDCONTROL__G_EN__SHIFT = 1,
	PXENG_CLUT0_UNSHADOWEDCONTROL__G_EN__MASK = 0x1,
	PXENG_CLUT0_UNSHADOWEDCONTROL__B_EN__SHIFT = 0,
	PXENG_CLUT0_UNSHADOWEDCONTROL__B_EN__MASK = 0x1,

	PXENG_CLUT0_CTRL__IDX_BITS__SHIFT = 8,
	PXENG_CLUT0_CTRL__IDX_BITS__MASK = 0xf,
	PXENG_CLUT0_CTRL__ALPHAINVERT__SHIFT = 6,
	PXENG_CLUT0_CTRL__ALPHAINVERT__MASK = 0x1,
	PXENG_CLUT0_CTRL__ALPHAMASK__SHIFT = 5,
	PXENG_CLUT0_CTRL__ALPHAMASK__MASK = 0x1,
	PXENG_CLUT0_CTRL__COL_8BIT__SHIFT = 4,
	PXENG_CLUT0_CTRL__COL_8BIT__MASK = 0x1,
	PXENG_CLUT0_CTRL__MODE__SHIFT = 0,
	PXENG_CLUT0_CTRL__MODE__MASK = 0x3
};

enum {
	PXENG_MATRIX0_STATCTL_OFS = 0x2c00,
	PXENG_MATRIX0_CTRL_OFS = 0x2c04,
	PXENG_MATRIX0_RED0_OFS = 0x2c08,
	PXENG_MATRIX0_RED1_OFS = 0x2c0c,
	PXENG_MATRIX0_GREEN0_OFS = 0x2c10,
	PXENG_MATRIX0_GREEN1_OFS = 0x2c14,
	PXENG_MATRIX0_BLUE0_OFS = 0x2c18,
	PXENG_MATRIX0_BLUE1_OFS = 0x2c1c,
};

enum {
	PXENG_MATRIX0_STATCTL__SHDEN__SHIFT = 0,
	PXENG_MATRIX0_STATCTL__SHDEN__MASK = 0x1,

	PXENG_MATRIX0_CTRL__ALPHAINVERT__SHIFT = 5,
	PXENG_MATRIX0_CTRL__ALPHAINVERT__MASK = 0x1,
	PXENG_MATRIX0_CTRL__ALPHAMASK__SHIFT = 4,
	PXENG_MATRIX0_CTRL__ALPHAMASK__MASK = 0x1,
	PXENG_MATRIX0_CTRL__MODE__SHIFT = 0,
	PXENG_MATRIX0_CTRL__MODE__MASK = 0x3,

	PXENG_MATRIX0_RED0__A12__SHIFT = 16,
	PXENG_MATRIX0_RED0__A12__MASK = 0x7ff,
	PXENG_MATRIX0_RED0__A11__SHIFT = 0,
	PXENG_MATRIX0_RED0__A11__MASK = 0x7ff,
	PXENG_MATRIX0_RED1__C1__SHIFT = 16,
	PXENG_MATRIX0_RED1__C1__MASK = 0x7ff,
	PXENG_MATRIX0_RED1__A13__SHIFT = 0,
	PXENG_MATRIX0_RED1__A13__MASK = 0x7ff,
	PXENG_MATRIX0_GREEN0__A22__SHIFT = 16,
	PXENG_MATRIX0_GREEN0__A22__MASK = 0x7ff,
	PXENG_MATRIX0_GREEN0__A21__SHIFT = 0,
	PXENG_MATRIX0_GREEN0__A21__MASK = 0x7ff,
	PXENG_MATRIX0_GREEN1__C2__SHIFT = 16,
	PXENG_MATRIX0_GREEN1__C2__MASK = 0x7ff,
	PXENG_MATRIX0_GREEN1__A23__SHIFT = 0,
	PXENG_MATRIX0_GREEN1__A23__MASK = 0x7ff,
	PXENG_MATRIX0_BLUE0__A32__SHIFT = 16,
	PXENG_MATRIX0_BLUE0__A32__MASK = 0x7ff,
	PXENG_MATRIX0_BLUE0__A31__SHIFT = 0,
	PXENG_MATRIX0_BLUE0__A31__MASK = 0x7ff,
	PXENG_MATRIX0_BLUE1__C3__SHIFT = 16,
	PXENG_MATRIX0_BLUE1__C3__MASK = 0x7ff,
	PXENG_MATRIX0_BLUE1__A33__SHIFT = 0,
	PXENG_MATRIX0_BLUE1__A33__MASK = 0x7ff,
};

enum {
	PXENG_HSCALER0_STATCTL_OFS = 0x3000,
	PXENG_HSCALER0_SETUP1_OFS = 0x3004,
	PXENG_HSCALER0_CTRL_OFS = 0x300c,
};

enum {
	PXENG_HSCALER0_STATCTL__SHDEN__SHIFT = 0,
	PXENG_HSCALER0_STATCTL__SHDEN__MASK = 0x1,

	PXENG_HSCALER0_SETUP1__SCALE_FACTOR__SHIFT = 0,
	PXENG_HSCALER0_SETUP1__SCALE_FACTOR__MASK = 0xffff,

	PXENG_HSCALER0_CTRL__OUTPUT_SIZE__SHIFT = 16,
	PXENG_HSCALER0_CTRL__OUTPUT_SIZE__MASK = 0x3fff,
	PXENG_HSCALER0_CTRL__FILTER_MODE__SHIFT = 8,
	PXENG_HSCALER0_CTRL__FILTER_MODE__MASK = 0x1,
	PXENG_HSCALER0_CTRL__SCALE_MODE__SHIFT = 4,
	PXENG_HSCALER0_CTRL__SCALE_MODE__MASK = 0x1,
	PXENG_HSCALER0_CTRL__MODE__SHIFT = 0,
	PXENG_HSCALER0_CTRL__MODE__MASK = 0x1,
};

enum {
	PXENG_VSCALER0_STATCTL_OFS = 0x3400,
	PXENG_VSCALER0_SETUP1_OFS = 0x3404,
	PXENG_VSCALER0_CTRL_OFS = 0x340c,
};

enum {
	PXENG_VSCALER0_STATCTL__SHDEN__SHIFT = 0,
	PXENG_VSCALER0_STATCTL__SHDEN__MASK = 0x1,

	PXENG_VSCALER0_SETUP1__SCALE_FACTOR__SHIFT = 0,
	PXENG_VSCALER0_SETUP1__SCALE_FACTOR__MASK = 0xffff,

	PXENG_VSCALER0_CTRL__OUTPUT_SIZE__SHIFT = 16,
	PXENG_VSCALER0_CTRL__OUTPUT_SIZE__MASK = 0x3fff,
	PXENG_VSCALER0_CTRL__FILTER_MODE__SHIFT = 8,
	PXENG_VSCALER0_CTRL__FILTER_MODE__MASK = 0x1,
	PXENG_VSCALER0_CTRL__SCALE_MODE__SHIFT = 4,
	PXENG_VSCALER0_CTRL__SCALE_MODE__MASK = 0x1,
	PXENG_VSCALER0_CTRL__MODE__SHIFT = 0,
	PXENG_VSCALER0_CTRL__MODE__MASK = 0x1,
};

enum {
	PXENG_FETCH4_LIGHT_BASEADDRESS_OFS = 0x3808
};

enum {
	PXE_F3_STATCTL_OFS = 0x3c00,
	PXE_F3_BRSTBUFMGT_OFS = 0x3c04,
	PXE_F3_BASEADDRESS_OFS = 0x3c08,
	PXE_F3_SOURCEBUFFERSTRIDE_OFS = 0x3c0c,
	PXE_F3_SOURCEBUFFERATTRIBUTES_OFS = 0x3c10,
	PXE_F3_FRAMEXOFFSET_OFS = 0x3c14,
	PXE_F3_FRAMEYOFFSET_OFS = 0x3c18,
	PXE_F3_FRAMEDIMENSIONS_OFS = 0x3c1c,
	PXE_F3_DELTAXX_OFS = 0x3c20,
	PXE_F3_DELTAXY_OFS = 0x3c24,
	PXE_F3_DELTAYX_OFS = 0x3c28,
	PXE_F3_DELTAYY_OFS = 0x3c2c,
	PXE_F3_SKIPWINDOWOFFSET_OFS = 0x3c30,
	PXE_F3_SKIPWINDOWDIMENSIONS_OFS = 0x3c34,
	PXE_F3_COLCOMPBITS_OFS = 0x3c38,
	PXE_F3_COLCOMPSHIFT_OFS = 0x3c3c,
	PXE_F3_CONSTANTCOLOR_OFS = 0x3c40,
	PXE_F3_TRANSPARENTCOLOR_OFS = 0x3c44,
	PXE_F3_FIRPOSITIONS_OFS = 0x3c48,
	PXE_F3_FIRCOEFFICIENTS_OFS = 0x3c4c,
	PXE_F3_WARPCONTROL_OFS = 0x3c50,
	PXE_F3_CTRL_OFS = 0x3c54,
	PXE_F3_CTRLTRIGGER_OFS = 0x3c58,
	PXE_F3_BURSTPROPS_OFS = 0x3c64,
};

enum {
	PXE_F3_STATCTL__TOGGLEFIELD__SHIFT = 9,
	PXE_F3_STATCTL__TOGGLEFIELD__MASK = 0x1,
	PXE_F3_STATCTL__SETFIELD__SHIFT = 8,
	PXE_F3_STATCTL__SETFIELD__MASK = 0x1,
	PXE_F3_STATCTL__CLOCKDISABLE__SHIFT = 5,
	PXE_F3_STATCTL__CLOCKDISABLE__MASK = 0x1,
	PXE_F3_STATCTL__SWRESET__SHIFT = 4,
	PXE_F3_STATCTL__SWRESET__MASK = 0x1,
	PXE_F3_STATCTL__SHDEN__SHIFT = 0,
	PXE_F3_STATCTL__SHDEN__MASK = 0x1,

	PXE_F3_BRSTBUFMGT__LINEMODE__SHIFT = 31,
	PXE_F3_BRSTBUFMGT__LINEMODE__MASK = 0x1,
	PXE_F3_BRSTBUFMGT__SETBURSTLENGTH__SHIFT = 8,
	PXE_F3_BRSTBUFMGT__SETBURSTLENGTH__MASK = 0x1f,
	PXE_F3_BRSTBUFMGT__SETNUMBUFFERS__SHIFT = 0,
	PXE_F3_BRSTBUFMGT__SETNUMBUFFERS__MASK = 0xff,

	PXE_F3_SOURCEBUFFERSTRIDE__STRIDE__SHIFT = 0,
	PXE_F3_SOURCEBUFFERSTRIDE__STRIDE__MASK = 0xffff,

	PXE_F3_SOURCEBUFFERATTRIBUTES__LINECOUNT__SHIFT = 16,
	PXE_F3_SOURCEBUFFERATTRIBUTES__LINECOUNT__MASK = 0x3fff,
	PXE_F3_SOURCEBUFFERATTRIBUTES__LINEWIDTH__SHIFT = 0,
	PXE_F3_SOURCEBUFFERATTRIBUTES__LINEWIDTH__MASK = 0x3fff,

	PXE_F3_FRAMEXOFFSET__FRAMEXOFFSET__SHIFT = 16,
	PXE_F3_FRAMEXOFFSET__FRAMEXOFFSET__MASK = 0xffff,
	PXE_F3_FRAMEXOFFSET__FRAMEXOFFSETDECIMALPLACES__SHIFT = 11,
	PXE_F3_FRAMEXOFFSET__FRAMEXOFFSETDECIMALPLACES__MASK = 0x1f,

	PXE_F3_FRAMEYOFFSET__FRAMEYOFFSET__SHIFT = 16,
	PXE_F3_FRAMEYOFFSET__FRAMEYOFFSET__MASK = 0xffff,
	PXE_F3_FRAMEYOFFSET__FRAMEYOFFSETDECIMALPLACES__SHIFT = 11,
	PXE_F3_FRAMEYOFFSET__FRAMEYOFFSETDECIMALPLACES__MASK = 0x1f,

	PXE_F3_FRAMEDIMENSIONS__FRAMEHEIGHT__SHIFT = 16,
	PXE_F3_FRAMEDIMENSIONS__FRAMEHEIGHT__MASK = 0x3fff,
	PXE_F3_FRAMEDIMENSIONS__FRAMEWIDTH__SHIFT = 0,
	PXE_F3_FRAMEDIMENSIONS__FRAMEWIDTH__MASK = 0x3fff,

	PXE_F3_DELTAXX__DELTAXX__SHIFT = 0,
	PXE_F3_DELTAXX__DELTAXX__MASK = 0x1ffffff,

	PXE_F3_DELTAXY__DELTAXY__SHIFT = 0,
	PXE_F3_DELTAXY__DELTAXY__MASK = 0x1ffffff,

	PXE_F3_DELTAYX__DELTAYX__SHIFT = 0,
	PXE_F3_DELTAYX__DELTAYX__MASK = 0x1ffffff,

	PXE_F3_DELTAYY__DELTAYY__SHIFT = 0,
	PXE_F3_DELTAYY__DELTAYY__MASK = 0x1ffffff,

	PXE_F3_SKIPWINDOWOFFSET__SKIPWINDOWYOFFSET__SHIFT = 16,
	PXE_F3_SKIPWINDOWOFFSET__SKIPWINDOWYOFFSET__MASK = 0x3fff,
	PXE_F3_SKIPWINDOWOFFSET__SKIPWINDOWXOFFSET__SHIFT = 0,
	PXE_F3_SKIPWINDOWOFFSET__SKIPWINDOWXOFFSET__MASK = 0x3fff,

	PXE_F3_SKIPWINDOWDIMENSIONS__SKIPWINDOWHEIGHT__SHIFT = 16,
	PXE_F3_SKIPWINDOWDIMENSIONS__SKIPWINDOWHEIGHT__MASK = 0x3fff,
	PXE_F3_SKIPWINDOWDIMENSIONS__SKIPWINDOWWIDTH__SHIFT = 0,
	PXE_F3_SKIPWINDOWDIMENSIONS__SKIPWINDOWWIDTH__MASK = 0x3fff,

	PXE_F3_COLCOMPBITS__COMPONENTBITSRED__SHIFT = 24,
	PXE_F3_COLCOMPBITS__COMPONENTBITSRED__MASK = 0xf,
	PXE_F3_COLCOMPBITS__COMPONENTBITSGREEN__SHIFT = 16,
	PXE_F3_COLCOMPBITS__COMPONENTBITSGREEN__MASK = 0xf,
	PXE_F3_COLCOMPBITS__COMPONENTBITSBLUE__SHIFT = 8,
	PXE_F3_COLCOMPBITS__COMPONENTBITSBLUE__MASK = 0xf,
	PXE_F3_COLCOMPBITS__COMPONENTBITSALPHA__SHIFT = 0,
	PXE_F3_COLCOMPBITS__COMPONENTBITSALPHA__MASK = 0xf,

	PXE_F3_COLCOMPSHIFT__COMPONENTSHIFTRED__SHIFT = 24,
	PXE_F3_COLCOMPSHIFT__COMPONENTSHIFTRED__MASK = 0x1f,
	PXE_F3_COLCOMPSHIFT__COMPONENTSHIFTGREEN__SHIFT = 16,
	PXE_F3_COLCOMPSHIFT__COMPONENTSHIFTGREEN__MASK = 0x1f,
	PXE_F3_COLCOMPSHIFT__COMPONENTSHIFTBLUE__SHIFT = 8,
	PXE_F3_COLCOMPSHIFT__COMPONENTSHIFTBLUE__MASK = 0x1f,
	PXE_F3_COLCOMPSHIFT__COMPONENTSHIFTALPHA__SHIFT = 0,
	PXE_F3_COLCOMPSHIFT__COMPONENTSHIFTALPHA__MASK = 0x1f,

	PXE_F3_CONSTANTCOLOR__CONSTANTCOLORRED__SHIFT = 24,
	PXE_F3_CONSTANTCOLOR__CONSTANTCOLORRED__MASK = 0xff,
	PXE_F3_CONSTANTCOLOR__CONSTANTCOLORGREEN__SHIFT = 16,
	PXE_F3_CONSTANTCOLOR__CONSTANTCOLORGREEN__MASK = 0xff,
	PXE_F3_CONSTANTCOLOR__CONSTANTCOLORBLUE__SHIFT = 8,
	PXE_F3_CONSTANTCOLOR__CONSTANTCOLORBLUE__MASK = 0xff,
	PXE_F3_CONSTANTCOLOR__CONSTANTCOLORALPHA__SHIFT = 0,
	PXE_F3_CONSTANTCOLOR__CONSTANTCOLORALPHA__MASK = 0xff,

	PXE_F3_TRANSPARENTCOLOR__TRANSPARENTCOLORRED__SHIFT = 20,
	PXE_F3_TRANSPARENTCOLOR__TRANSPARENTCOLORRED__MASK = 0x3ff,
	PXE_F3_TRANSPARENTCOLOR__TRANSPARENTCOLORGREEN__SHIFT = 10,
	PXE_F3_TRANSPARENTCOLOR__TRANSPARENTCOLORGREEN__MASK = 0x3ff,
	PXE_F3_TRANSPARENTCOLOR__TRANSPARENTCOLORBLUE__SHIFT = 0,
	PXE_F3_TRANSPARENTCOLOR__TRANSPARENTCOLORBLUE__MASK = 0x3ff,

	PXE_F3_FIRPOSITIONS__FIRPOSITION3__SHIFT = 12,
	PXE_F3_FIRPOSITIONS__FIRPOSITION3__MASK = 0xf,
	PXE_F3_FIRPOSITIONS__FIRPOSITION2__SHIFT = 8,
	PXE_F3_FIRPOSITIONS__FIRPOSITION2__MASK = 0xf,
	PXE_F3_FIRPOSITIONS__FIRPOSITION1__SHIFT = 4,
	PXE_F3_FIRPOSITIONS__FIRPOSITION1__MASK = 0xf,
	PXE_F3_FIRPOSITIONS__FIRPOSITION0__SHIFT = 0,
	PXE_F3_FIRPOSITIONS__FIRPOSITION0__MASK = 0xf,

	PXE_F3_FIRCOEFFICIENTS__FIRCOEFFICIENT3__SHIFT = 24,
	PXE_F3_FIRCOEFFICIENTS__FIRCOEFFICIENT3__MASK = 0xff,
	PXE_F3_FIRCOEFFICIENTS__FIRCOEFFICIENT2__SHIFT = 16,
	PXE_F3_FIRCOEFFICIENTS__FIRCOEFFICIENT2__MASK = 0xff,
	PXE_F3_FIRCOEFFICIENTS__FIRCOEFFICIENT1__SHIFT = 8,
	PXE_F3_FIRCOEFFICIENTS__FIRCOEFFICIENT1__MASK = 0xff,
	PXE_F3_FIRCOEFFICIENTS__FIRCOEFFICIENT0__SHIFT = 0,
	PXE_F3_FIRCOEFFICIENTS__FIRCOEFFICIENT0__MASK = 0xff,

	PXE_F3_WARPCONTROL__WARPSYMMETRICOFFSET__SHIFT = 12,
	PXE_F3_WARPCONTROL__WARPSYMMETRICOFFSET__MASK = 0x1,
	PXE_F3_WARPCONTROL__WARPCOORDINATEMODE__SHIFT = 8,
	PXE_F3_WARPCONTROL__WARPCOORDINATEMODE__MASK = 0x3,
	PXE_F3_WARPCONTROL__WARPBITSPERPIXEL__SHIFT = 0,
	PXE_F3_WARPCONTROL__WARPBITSPERPIXEL__MASK = 0x3f,

	PXE_F3_CTRL__BITSPERPIXEL__SHIFT = 0,
	PXE_F3_CTRL__BITSPERPIXEL__MASK = 0x3f,
	PXE_F3_CTRL__ALPHA_MULTIPLY__SHIFT = 8,
	PXE_F3_CTRL__ALPHA_MULTIPLY__MASK = 1,
	PXE_F3_CTRL__TILEMODE__SHIFT = 12,
	PXE_F3_CTRL__TILEMODE__MASK = 0x3,

	PXE_F3_CTRLTRIGGER__EMPTYFRAME__SHIFT = 1,
	PXE_F3_CTRLTRIGGER__EMPTYFRAME__MASK = 0x1,
	PXE_F3_CTRLTRIGGER__SHDTOKGEN__SHIFT = 0,
	PXE_F3_CTRLTRIGGER__SHDTOKGEN__MASK = 0x1,

	PXE_F3_BURSTPROPS__MAXBURSTLENGTH__SHIFT = 8,
	PXE_F3_BURSTPROPS__MAXBURSTLENGTH__MASK = 0x1f,
	PXE_F3_BURSTPROPS__MAXNUMBUFFERS__SHIFT = 0,
	PXE_F3_BURSTPROPS__MAXNUMBUFFERS__MASK = 0xff,
};

enum {
	PXENG_EXTDST0_STATCTL_OFS = 0x4000
};

enum {
	PXENG_EXTDST0_STATCTL__PERFCOUNTMODE__SHIFT = 4,
	PXENG_EXTDST0_STATCTL__PERFCOUNTMODE__MASK = 0x1,
	PXENG_EXTDST0_STATCTL__KICK_MODE__SHIFT = 0,
	PXENG_EXTDST0_STATCTL__KICK_MODE__MASK = 0x1
};

enum {
	PXENG_LYRBLND0_STATCTL_OFS = 0x4400,
	PXENG_LYRBLND0_CTRL_OFS = 0x4404
};

enum {
	PXENG_LYRBLND0_STATCTL__SHDLDSEL__SHIFT = 2,
	PXENG_LYRBLND0_STATCTL__SHDLDSEL__MASK = 0x1,
	PXENG_LYRBLND0_STATCTL__SHDTOKEPSEC__SHIFT = 1,
	PXENG_LYRBLND0_STATCTL__SHDTOKEPSEC__MASK = 0x1,
	PXENG_LYRBLND0_STATCTL__SHDEN__SHIFT = 0,
	PXENG_LYRBLND0_STATCTL__SHDEN__MASK = 0x1,

	PXENG_LYRBLND0_CTRL__ALPHA__SHIFT = 24,
	PXENG_LYRBLND0_CTRL__ALPHA__MASK = 0xff,
	PXENG_LYRBLND0_CTRL__ALPHAMASKMODE__SHIFT = 20,
	PXENG_LYRBLND0_CTRL__ALPHAMASKMODE__MASK = 0x7,
	PXENG_LYRBLND0_CTRL__SEC_A_BLD_FUNC__SHIFT = 16,
	PXENG_LYRBLND0_CTRL__SEC_A_BLD_FUNC__MASK = 0x7,
	PXENG_LYRBLND0_CTRL__PRIM_A_BLD_FUNC__SHIFT = 12,
	PXENG_LYRBLND0_CTRL__PRIM_A_BLD_FUNC__MASK = 0x7,
	PXENG_LYRBLND0_CTRL__SEC_C_BLD_FUNC__SHIFT = 8,
	PXENG_LYRBLND0_CTRL__SEC_C_BLD_FUNC__MASK = 0x7,
	PXENG_LYRBLND0_CTRL__PRIM_C_BLD_FUNC__SHIFT = 4,
	PXENG_LYRBLND0_CTRL__PRIM_C_BLD_FUNC__MASK = 0x7,
	PXENG_LYRBLND0_CTRL__ALPHAMASKENABLE__SHIFT = 2,
	PXENG_LYRBLND0_CTRL__ALPHAMASKENABLE__MASK = 0x1,
	PXENG_LYRBLND0_CTRL__MODE__SHIFT = 0,
	PXENG_LYRBLND0_CTRL__MODE__MASK = 0x1
};

enum {
	PXENG_LYRBLND1_STATCTL_OFS = 0x4800,
	PXENG_LYRBLND1_CTRL_OFS = 0x4804
};

enum {
	PXENG_LYRBLND1_STATCTL__SHDLDSEL__SHIFT = 2,
	PXENG_LYRBLND1_STATCTL__SHDLDSEL__MASK = 0x1,
	PXENG_LYRBLND1_STATCTL__SHDTOKEPSEC__SHIFT = 1,
	PXENG_LYRBLND1_STATCTL__SHDTOKEPSEC__MASK = 0x1,
	PXENG_LYRBLND1_STATCTL__SHDEN__SHIFT = 0,
	PXENG_LYRBLND1_STATCTL__SHDEN__MASK = 0x1,

	PXENG_LYRBLND1_CTRL__ALPHA__SHIFT = 24,
	PXENG_LYRBLND1_CTRL__ALPHA__MASK = 0xff,
	PXENG_LYRBLND1_CTRL__ALPHAMASKMODE__SHIFT = 20,
	PXENG_LYRBLND1_CTRL__ALPHAMASKMODE__MASK = 0x7,
	PXENG_LYRBLND1_CTRL__SEC_A_BLD_FUNC__SHIFT = 16,
	PXENG_LYRBLND1_CTRL__SEC_A_BLD_FUNC__MASK = 0x7,
	PXENG_LYRBLND1_CTRL__PRIM_A_BLD_FUNC__SHIFT = 12,
	PXENG_LYRBLND1_CTRL__PRIM_A_BLD_FUNC__MASK = 0x7,
	PXENG_LYRBLND1_CTRL__SEC_C_BLD_FUNC__SHIFT = 8,
	PXENG_LYRBLND1_CTRL__SEC_C_BLD_FUNC__MASK = 0x7,
	PXENG_LYRBLND1_CTRL__PRIM_C_BLD_FUNC__SHIFT = 4,
	PXENG_LYRBLND1_CTRL__PRIM_C_BLD_FUNC__MASK = 0x7,
	PXENG_LYRBLND1_CTRL__ALPHAMASKENABLE__SHIFT = 2,
	PXENG_LYRBLND1_CTRL__ALPHAMASKENABLE__MASK = 0x1,
	PXENG_LYRBLND1_CTRL__MODE__SHIFT = 0,
	PXENG_LYRBLND1_CTRL__MODE__MASK = 0x1
};

enum {
	DISPENG_FRAMEGEN0_LOCK_UNLOCK_OFS = 0x5400,
	DISPENG_FRAMEGEN0_LOCK_STATUS_OFS = 0x5404,
	DISPENG_FRAMEGEN0_FGSTCTRL_OFS = 0x5408,
	DISPENG_FRAMEGEN0_HTCFG1_OFS = 0x540c,
	DISPENG_FRAMEGEN0_HTCFG2_OFS = 0x5410,
	DISPENG_FRAMEGEN0_VTCFG1_OFS = 0x5414,
	DISPENG_FRAMEGEN0_VTCFG2_OFS = 0x5418,
	DISPENG_FRAMEGEN0_INT0CFG_OFS = 0x541c,
	DISPENG_FRAMEGEN0_PKICKCONFIG_OFS = 0x542c,
	DISPENG_FRAMEGEN0_PACFG_OFS = 0x5434,
	DISPENG_FRAMEGEN0_FGLNCTRL_OFS = 0x5438,
	DISPENG_FRAMEGEN0_FGINPANIC_OFS = 0x543c,
	DISPENG_FRAMEGEN0_FGCCR_OFS = 0x5440,
	DISPENG_FRAMEGEN0_FGENABLE_OFS = 0x5444,
	DISPENG_FRAMEGEN0_FGSLR_OFS = 0x5448,
	DISPENG_FRAMEGEN0_FGENSTS_OFS = 0x544c,

	DISPENG_FRAMEGEN0_FGSTCTRL__SHDTOKEPPRIM__SHIFT = 3,
	DISPENG_FRAMEGEN0_FGSTCTRL__SHDTOKEPPRIM__MASK = 0x1,
	DISPENG_FRAMEGEN0_FGSTCTRL__SHDLDSEL__SHIFT = 1,
	DISPENG_FRAMEGEN0_FGSTCTRL__SHDLDSEL__MASK = 0x3,
	DISPENG_FRAMEGEN0_FGSTCTRL__SHDEN__SHIFT = 0,
	DISPENG_FRAMEGEN0_FGSTCTRL__SHDEN__MASK = 0x1,

	DISPENG_FRAMEGEN0_HTCFG1__HTOTAL__SHIFT = 16,
	DISPENG_FRAMEGEN0_HTCFG1__HTOTAL__MASK = 0x3fff,
	DISPENG_FRAMEGEN0_HTCFG1__HACT__SHIFT = 0,
	DISPENG_FRAMEGEN0_HTCFG1__HACT__MASK = 0x3fff,

	DISPENG_FRAMEGEN0_HTCFG2__HSEN__SHIFT = 31,
	DISPENG_FRAMEGEN0_HTCFG2__HSEN__MASK = 0x1,
	DISPENG_FRAMEGEN0_HTCFG2__HSBP__SHIFT = 16,
	DISPENG_FRAMEGEN0_HTCFG2__HSBP__MASK = 0x3fff,
	DISPENG_FRAMEGEN0_HTCFG2__HSYNC__SHIFT = 0,
	DISPENG_FRAMEGEN0_HTCFG2__HSYNC__MASK = 0x3fff,

	DISPENG_FRAMEGEN0_VTCFG1__VTOTAL__SHIFT = 16,
	DISPENG_FRAMEGEN0_VTCFG1__VTOTAL__MASK = 0x3fff,
	DISPENG_FRAMEGEN0_VTCFG1__VACT__SHIFT = 0,
	DISPENG_FRAMEGEN0_VTCFG1__VACT__MASK = 0x3fff,

	DISPENG_FRAMEGEN0_VTCFG2__VSEN__SHIFT = 31,
	DISPENG_FRAMEGEN0_VTCFG2__VSEN__MASK = 0x1,
	DISPENG_FRAMEGEN0_VTCFG2__VSBP__SHIFT = 16,
	DISPENG_FRAMEGEN0_VTCFG2__VSBP__MASK = 0x3fff,
	DISPENG_FRAMEGEN0_VTCFG2__VSYNC__SHIFT = 0,
	DISPENG_FRAMEGEN0_VTCFG2__VSYNC__MASK = 0x3fff,

	DISPENG_FRAMEGEN0_PKICKCONFIG__PKICKEN__SHIFT = 31,
	DISPENG_FRAMEGEN0_PKICKCONFIG__PKICKEN__MASK = 0x1,
	DISPENG_FRAMEGEN0_PKICKCONFIG__PKICKROW__SHIFT = 16,
	DISPENG_FRAMEGEN0_PKICKCONFIG__PKICKROW__MASK = 0x3fff,
	DISPENG_FRAMEGEN0_PKICKCONFIG__PKICKINT0EN__SHIFT = 15,
	DISPENG_FRAMEGEN0_PKICKCONFIG__PKICKINT0EN__MASK = 0x1,
	DISPENG_FRAMEGEN0_PKICKCONFIG__PKICKCOL__SHIFT = 0,
	DISPENG_FRAMEGEN0_PKICKCONFIG__PKICKCOL__MASK = 0x3fff,

	DISPENG_FRAMEGEN0_PACFG__PSTARTY__SHIFT = 16,
	DISPENG_FRAMEGEN0_PACFG__PSTARTY__MASK = 0x3fff,
	DISPENG_FRAMEGEN0_PACFG__PSTARTX__SHIFT = 0,
	DISPENG_FRAMEGEN0_PACFG__PSTARTX__MASK = 0x3fff,

	DISPENG_FRAMEGEN0_FGLNCTRL__FGDM__SHIFT = 0,
	DISPENG_FRAMEGEN0_FGLNCTRL__FGDM__MASK = 0x7,

	DISPENG_FRAMEGEN0_FGCCR__CCALPHA__SHIFT = 24,
	DISPENG_FRAMEGEN0_FGCCR__CCALPHA__MASK = 0x1,
	DISPENG_FRAMEGEN0_FGCCR__CCRED__SHIFT = 16,
	DISPENG_FRAMEGEN0_FGCCR__CCRED__MASK = 0xff,
	DISPENG_FRAMEGEN0_FGCCR__CCGREEN__SHIFT = 8,
	DISPENG_FRAMEGEN0_FGCCR__CCGREEN__MASK = 0xff,
	DISPENG_FRAMEGEN0_FGCCR__CCBLUE__SHIFT = 0,
	DISPENG_FRAMEGEN0_FGCCR__CCBLUE__MASK = 0xff,

	DISPENG_FRAMEGEN0_FGENABLE__FGEN__SHIFT = 0,
	DISPENG_FRAMEGEN0_FGENABLE__FGEN__MASK = 0x1,

	DISPENG_FRAMEGEN0_FGSLR__SHDTOKGEN__SHIFT = 0,
	DISPENG_FRAMEGEN0_FGSLR__SHDTOKGEN__MASK = 0x1
};

#endif
