#ifndef __MB8AC0300_FB_H__
#define __MB8AC0300_FB_H__

#include <linux/mutex.h>

#include <video/fdb.h>

struct picapdc_par {
	struct f_fdb_child fdb_child;
	struct f_fdb_child *source; /* our owner, eg, drm driver, if any */
	int id;
	int irq;
	struct device *dev;
	u32 pseudo_palette[16];
	u32 __iomem *base;
	dma_addr_t fbpaddr; /* real start of allocation */
	void *fb_va;
	u32 framesize;
	struct mutex lock;
	bool simple;
	u32 frame_index;
	struct completion completion;
	bool completion_pending;

	unsigned int pixel_format; /* fourcc */
	int bits_per_pixel;
};

#define f_par_from_fdb_child(_fc) \
		container_of((_fc), struct picapdc_par, fdb_child)

enum {
	PICAPDC_H_CTR_OFS = 0,
	PICAPDC_H_ADDR_TIME_OFS = 4,
	PICAPDC_H_RIGHT_BORDER_OFS = 8,
	PICAPDC_H_BLANK_OFS = 0x0c,
	PICAPDC_H_SYNC_OFS = 0x10,
	PICAPDC_H_BACKPORCH_OFS = 0x14,
	PICAPDC_H_LEFT_BORDER_OFS = 0x18,
	PICAPDC_H_INTERRUPT_OFS = 0x1c,
	PICAPDC_H_DMA_OFS = 0x20,
	PICAPDC_V_COUNTER_OFS = 0x24,
	PICAPDC_V_ADDR_TIME_OFS = 0x28,
	PICAPDC_V_BOTTOM_BORDER_OFS = 0x2c,
	PICAPDC_V_BLANK_OFS = 0x30,
	PICAPDC_V_SYNC_OFS = 0x34,
	PICAPDC_V_BACKPORCH_OFS = 0x38,
	PICAPDC_V_TOP_BORDER_OFS = 0x3c,
	PICAPDC_V_INTERRUPT_OFS = 0x40,
	PICAPDC_V_INCREMENT_H_OFS = 0x44,
	PICAPDC_SIGNAL_POL_OFS = 0x48,
	PICAPDC_SIGNAL_BORDER_COLOUR_OFS = 0x4c,
	PICAPDC_H_STATUS_OFS = 0x50,
	PICAPDC_V_STATUS_OFS = 0x54,
	PICAPDC_SRC_OFS = 0x58,
	PICAPDC_OUT_OFS = 0x5c,
	PICAPDC_H_PIC_BORDER_OFS = 0x60,
	PICAPDC_V_PIC_BORDER_OFS = 0x64,
	PICAPDC_ADR_FB0_OFS = 0x68,
	PICAPDC_ADR_FB1_OFS = 0x6c,
	PICAPDC_MODE_OFS = 0x70,
	PICAPDC_START_OFS = 0x74,
	PICAPDC_SWAP_OFS = 0x78,
	PICAPDC_STATUS_OFS = 0x7c,
	PICAPDC_GAMMA_ADS_OFS = 0x80,
	PICAPDC_GAMMA_DATA_OFS = 0x84,
	PICAPDC_DATA_OFS = 0x90,

};

enum {
	PICAPDC_H_CTR__SIZE__SHIFT = 0,
	PICAPDC_H_CTR__SIZE__MASK = 0xfff,

	PICAPDC_H_ADDR_TIME__START__SHIFT = 0,
	PICAPDC_H_ADDR_TIME__START__MASK = 0xfff,

	PICAPDC_H_RIGHT_BORDER__START__SHIFT = 0,
	PICAPDC_H_RIGHT_BORDER__START__MASK = 0xfff,

	PICAPDC_H_BLANK__START__SHIFT = 0,
	PICAPDC_H_BLANK__START__MASK = 0xfff,

	PICAPDC_H_SYNC__START__SHIFT = 0,
	PICAPDC_H_SYNC__START__MASK = 0xfff,

	PICAPDC_H_BACKPORCH__START__SHIFT = 0,
	PICAPDC_H_BACKPORCH__START__MASK = 0xfff,

	PICAPDC_H_LEFT_BORDER__START__SHIFT = 0,
	PICAPDC_H_LEFT_BORDER__START__MASK = 0xfff,

	PICAPDC_H_INTERRUPT__START__SHIFT = 0,
	PICAPDC_H_INTERRUPT__START__MASK = 0xfff,
	PICAPDC_H_INTERRUPT__END__SHIFT = 16,
	PICAPDC_H_INTERRUPT__END__MASK = 0xfff,

	PICAPDC_H_DMA__START__SHIFT = 0,
	PICAPDC_H_DMA__START__MASK = 0xfff,
	PICAPDC_H_DMA__END__SHIFT = 16,
	PICAPDC_H_DMA__END__MASK = 0xfff,

	PICAPDC_V_COUNTER__SIZE__SHIFT = 0,
	PICAPDC_V_COUNTER__SIZE__MASK = 0xfff,

	PICAPDC_V_ADDR_TIME__START__SHIFT = 0,
	PICAPDC_V_ADDR_TIME__START__MASK = 0xfff,

	PICAPDC_V_BOTTOM_BORDER__START__SHIFT = 0,
	PICAPDC_V_BOTTOM_BORDER__START__MASK = 0xfff,

	PICAPDC_V_BLANK__START__SHIFT = 0,
	PICAPDC_V_BLANK__START__MASK = 0xfff,

	PICAPDC_V_SYNC__START__SHIFT = 0,
	PICAPDC_V_SYNC__START__MASK = 0xfff,

	PICAPDC_V_BACKPORCH__START__SHIFT = 0,
	PICAPDC_V_BACKPORCH__START__MASK = 0xfff,

	PICAPDC_V_TOP_BORDER__START__SHIFT = 0,
	PICAPDC_V_TOP_BORDER__START__MASK = 0xfff,

	PICAPDC_V_INTERRUPT__START__SHIFT = 0,
	PICAPDC_V_INTERRUPT__START__MASK = 0xfff,
	PICAPDC_V_INTERRUPT__END__SHIFT = 16,
	PICAPDC_V_INTERRUPT__END__MASK = 0xfff,

	PICAPDC_V_INCREMENT_H__VALUE__SHIFT = 0,
	PICAPDC_V_INCREMENT_H__VALUE__MASK = 0xfff,

	PICAPDC_SIGNAL_POL__HSYNC__SHIFT = 0,
	PICAPDC_SIGNAL_POL__HSYNC__MASK = 1,

	PICAPDC_SIGNAL_POL__VSYNC__SHIFT = 4,
	PICAPDC_SIGNAL_POL__VSYNC__MASK = 1,

	PICAPDC_SIGNAL_BORDER_COLOUR__RED__SHIFT = 0,
	PICAPDC_SIGNAL_BORDER_COLOUR__RED__MASK = 0xff,
	PICAPDC_SIGNAL_BORDER_COLOUR__GREEN__SHIFT = 8,
	PICAPDC_SIGNAL_BORDER_COLOUR__GREEN__MASK = 0xff,
	PICAPDC_SIGNAL_BORDER_COLOUR__BLUE__SHIFT = 16,
	PICAPDC_SIGNAL_BORDER_COLOUR__BLUE__MASK = 0xff,

	PICAPDC_H_STATUS__HCOUNT__SHIFT = 0,
	PICAPDC_H_STATUS__HCOUNT__MASK = 0xfff,

	PICAPDC_V_STATUS__VCOUNT__SHIFT = 0,
	PICAPDC_V_STATUS__VCOUNT__MASK = 0xfff,

	PICAPDC_SRC__WIDTH__SHIFT = 0,
	PICAPDC_SRC__WIDTH__MASK = 0xfff,
	PICAPDC_SRC__HEIGHT__SHIFT = 16,
	PICAPDC_SRC__HEIGHT__MASK = 0xfff,

	PICAPDC_OUT__WIDTH__SHIFT = 0,
	PICAPDC_OUT__WIDTH__MASK = 0xfff,
	PICAPDC_OUT__HEIGHT__SHIFT = 16,
	PICAPDC_OUT__HEIGHT__MASK = 0xfff,

	PICAPDC_H_PIC_BORDER__START__SHIFT = 0,
	PICAPDC_H_PIC_BORDER__START__MASK = 0xfff,
	PICAPDC_H_PIC_BORDER__END__SHIFT = 16,
	PICAPDC_H_PIC_BORDER__END__MASK = 0xfff,

	PICAPDC_V_PIC_BORDER__START__SHIFT = 0,
	PICAPDC_V_PIC_BORDER__START__MASK = 0xfff,
	PICAPDC_V_PIC_BORDER__END__SHIFT = 16,
	PICAPDC_V_PIC_BORDER__END__MASK = 0xfff,



	PICAPDC_MODE_R8G8B8A8 = 0,
	PICAPDC_MODE_R8G8B8 = 1,
	PICAPDC_MODE_R5G6B5 = 2,
	PICAPDC_MODE_R5G5B5A1 = 3,
	PICAPDC_MODE_R4G4B4A4 = 4,

	PICAPDC_MODE__FORMAT__SHIFT = 0,
	PICAPDC_MODE__FORMAT__MASK = 7,
	PICAPDC_MODE__VSYNC_START__SHIFT = 4,
	PICAPDC_MODE__VSYNC_START__MASK = 1,
	PICAPDC_MODE__BURST_LENGTH__SHIFT = 8,
	PICAPDC_MODE__BURST_LENGTH__MASK = 3,
	PICAPDC_MODE__REQ_INTERVAL__SHIFT = 16,
	PICAPDC_MODE__REQ_INTERVAL__MASK = 0xffff,

	PICAPDC_START__START__SHIFT = 0,
	PICAPDC_START__START__MASK = 1,
	PICAPDC_START__INT_MASK_H__SHIFT = 8,
	PICAPDC_START__INT_MASK_H__MASK = 1,
	PICAPDC_START__INT_MASK_V__SHIFT = 9,
	PICAPDC_START__INT_MASK_V__MASK = 1,
	PICAPDC_START__INT_MASK_ERR__SHIFT = 10,
	PICAPDC_START__INT_MASK_ERR__MASK = 1,
	PICAPDC_START__OUT_EN__SHIFT = 16,
	PICAPDC_START__OUT_EN__MASK = 1,

	PICAPDC_SWAP__NEXT__SHIFT = 0,
	PICAPDC_SWAP__NEXT__MASK = 1,
	PICAPDC_SWAP__AUTOSWAP__SHIFT = 4,
	PICAPDC_SWAP__AUTOSWAP__MASK = 1,
	PICAPDC_SWAP__FIFO_RESET__SHIFT = 8,
	PICAPDC_SWAP__FIFO_RESET__MASK = 1,
	PICAPDC_SWAP__INT_CLR_H__SHIFT = 16,
	PICAPDC_SWAP__INT_CLR_H__MASK = 1,
	PICAPDC_SWAP__INT_CLR_V__SHIFT = 17,
	PICAPDC_SWAP__INT_CLR_V__MASK = 1,
	PICAPDC_SWAP__INT_CLR_ERR__SHIFT = 18,
	PICAPDC_SWAP__INT_CLR_ERR__MASK = 1,

	PICAPDC_STATUS__V_INT__SHIFT = 0,
	PICAPDC_STATUS__V_INT__MASK = 1,
	PICAPDC_STATUS__H_INT__SHIFT = 1,
	PICAPDC_STATUS__H_INT__MASK = 1,
	PICAPDC_STATUS__CUR_BANK__SHIFT = 4,
	PICAPDC_STATUS__CUR_BANK__MASK = 1,
	PICAPDC_STATUS__V_SYNC__SHIFT = 8,
	PICAPDC_STATUS__V_SYNC__MASK = 1,
	PICAPDC_STATUS__V_BLANK__SHIFT = 9,
	PICAPDC_STATUS__V_BLANK__MASK = 1,
	PICAPDC_STATUS__V_ACTIVE__SHIFT = 10,
	PICAPDC_STATUS__V_ACTIVE__MASK = 1,
	PICAPDC_STATUS__H_SYNC__SHIFT = 12,
	PICAPDC_STATUS__H_SYNC__MASK = 1,
	PICAPDC_STATUS__H_BLANK__SHIFT = 13,
	PICAPDC_STATUS__H_BLANK__MASK = 1,
	PICAPDC_STATUS__H_ACTIVE__SHIFT = 14,
	PICAPDC_STATUS__H_ACTIVE__MASK = 1,
	PICAPDC_STATUS__ERROR__SHIFT = 15,
	PICAPDC_STATUS__ERROR__MASK = 1,

	PICAPDC_GAMMA_ADS__ADS__SHIFT = 0,
	PICAPDC_GAMMA_ADS__ADS__MASK = 0xff,

	PICAPDC_GAMMA_DATA__RED__SHIFT = 0,
	PICAPDC_GAMMA_DATA__RED__MASK = 0xff,
	PICAPDC_GAMMA_DATA__GREEN__SHIFT = 8,
	PICAPDC_GAMMA_DATA__GREEN__MASK = 0xff,
	PICAPDC_GAMMA_DATA__BLUE__SHIFT = 16,
	PICAPDC_GAMMA_DATA__BLUE__MASK = 0xff,

	PICAPDC_DATA__SIZE__SHIFT = 0,
	PICAPDC_DATA__SIZE__MASK = 0xffffffff,
};


#endif

