obj-$(CONFIG_PCIE_F_PCIE2_DMXH) += pcie_f_pcie2_dme.o
obj-$(CONFIG_SYSOC_F_PCIE_PCIE2_DMXH) += sysoc_pcie.o
obj-$(CONFIG_PCI_MVEBU) += pci-mvebu.o
obj-$(CONFIG_PCIE_DW) += pcie-designware.o
obj-$(CONFIG_PCI_MSI) += pcie_f_pcie2_dme_msi.o
