/*
 * XMC4x00 USIC
 *
 * Copyright 2015-2016 Andreas Färber
 *
 * License: GPL-2.0+
 */
#ifndef __MFD_XMC4000_H
#define __MFD_XMC4000_H

#define USICx_CHy_CCFG		0x04
#define USICx_CHy_KSCFG		0x0C
#define USICx_CHy_FDR		0x10
#define USICx_CHy_BRG		0x14
#define USICx_CHy_DX0CR		0x1C
#define USICx_CHy_DX1CR		0x20
#define USICx_CHy_DX2CR		0x24
#define USICx_CHy_DX3CR		0x28
#define USICx_CHy_DX4CR		0x2C
#define USICx_CHy_DX5CR		0x30
#define USICx_CHy_SCTR		0x34
#define USICx_CHy_TCSR		0x38
#define USICx_CHy_PCR		0x3C
#define USICx_CHy_CCR		0x40
#define USICx_CHy_TBCTR		0x108
#define USICx_CHy_RBCTR		0x10C
#define USICx_CHy_TRBSR		0x114
#define USICx_CHy_IN0		0x180

#define USICx_CHy_CCFG_SSC	BIT(0)
#define USICx_CHy_CCFG_ASC	BIT(1)
#define USICx_CHy_CCFG_IIC	BIT(2)
#define USICx_CHy_CCFG_IIS	BIT(3)

#define USICx_CHy_KSCFG_MODEN		BIT(0)
#define USICx_CHy_KSCFG_BPMODEN		BIT(1)

#define USICx_CHy_FDR_STEP_OFFSET	0
#define USICx_CHy_FDR_STEP_MASK		(0x3ff << USICx_CHy_FDR_STEP_OFFSET)

#define USICx_CHy_FDR_DM_OFFSET		14
#define USICx_CHy_FDR_DM_NORMAL		(0x1 << USICx_CHy_FDR_DM_OFFSET)
#define USICx_CHy_FDR_DM_FRAC		(0x2 << USICx_CHy_FDR_DM_OFFSET)
#define USICx_CHy_FDR_DM_MASK		(0x3 << USICx_CHy_FDR_DM_OFFSET)

#define USICx_CHy_BRG_CTQSEL_OFFSET	6
#define USICx_CHy_BRG_CTQSEL_PDIV	(0x0 << USICx_CHy_BRG_CTQSEL_OFFSET)
#define USICx_CHy_BRG_CTQSEL_PPP	(0x1 << USICx_CHy_BRG_CTQSEL_OFFSET)
#define USICx_CHy_BRG_CTQSEL_SCLK	(0x2 << USICx_CHy_BRG_CTQSEL_OFFSET)
#define USICx_CHy_BRG_CTQSEL_MCLK	(0x3 << USICx_CHy_BRG_CTQSEL_OFFSET)
#define USICx_CHy_BRG_CTQSEL_MASK	(0x3 << USICx_CHy_BRG_CTQSEL_OFFSET)

#define USICx_CHy_BRG_DCTQ_OFFSET	10
#define USICx_CHy_BRG_DCTQ_MASK		(0x1f << USICx_CHy_BRG_DCTQ_OFFSET)

#define USICx_CHy_BRG_PDIV_OFFSET	16
#define USICx_CHy_BRG_PDIV_MASK		(0x3ff << USICx_CHy_BRG_PDIV_OFFSET)

#define USICx_CHy_BRG_SCLKCFG_OFFSET	30
#define USICx_CHy_BRG_SCLKCFG_PASSIVE_1	BIT(USICx_CHy_BRG_SCLKCFG_OFFSET)
#define USICx_CHy_BRG_SCLKCFG_DELAY	BIT(USICx_CHy_BRG_SCLKCFG_OFFSET + 1)
#define USICx_CHy_BRG_SCLKCFG_MASK	(0x3 << USICx_CHy_BRG_SCLKCFG_OFFSET)

/* n != 1 */
#define USICx_CHy_DXnCR_INSW		BIT(4)

#define USICx_CHy_DXnCR_DSEL_OFFSET	0
#define USICx_CHy_DXnCR_DSEL_MASK	(0x7 << USICx_CHy_DXnCR_DSEL_OFFSET)

#define USICx_CHy_SCTR_SDIR_MSB		BIT(0)
#define USICx_CHy_SCTR_PDL_1		BIT(1)

#define USICx_CHy_SCTR_TRM_OFFSET	8
#define USICx_CHy_SCTR_TRM_MASK		(0x3 << USICx_CHy_SCTR_TRM_OFFSET)

#define USICx_CHy_SCTR_FLE_OFFSET	16
#define USICx_CHy_SCTR_FLE_MASK		(0x3f << USICx_CHy_SCTR_FLE_OFFSET)

#define USICx_CHy_SCTR_WLE_OFFSET	24
#define USICx_CHy_SCTR_WLE_MASK		(0xf << USICx_CHy_SCTR_WLE_OFFSET)

#define USICx_CHy_TCSR_HPCMD		BIT(4)
#define USICx_CHy_TCSR_TDSSM		BIT(8)

#define USICx_CHy_TCSR_TDEN_OFFSET	10
#define USICx_CHy_TCSR_TDEN_MASK	(0x3 << USICx_CHy_TCSR_TDEN_OFFSET)

#define USICx_CHy_CCR_MODE_DISABLED	0x0
#define USICx_CHy_CCR_MODE_SSC		0x1
#define USICx_CHy_CCR_MODE_ASC		0x2
#define USICx_CHy_CCR_MODE_IIS		0x3
#define USICx_CHy_CCR_MODE_IIC		0x4
#define USICx_CHy_CCR_MODE_MASK		0xf

#define USICx_CHy_CCR_HPCEN_OFFSET	6
#define USICx_CHy_CCR_HPCEN_MASK	(0x3 << USICx_CHy_CCR_HPCEN_OFFSET)

#define USICx_CHy_TBCTR_LIMIT_OFFSET	8
#define USICx_CHy_TBCTR_LIMIT_MASK	(0x3f << USICx_CHy_TBCTR_LIMIT_OFFSET)

#define USICx_CHy_RBCTR_LIMIT_OFFSET	8
#define USICx_CHy_RBCTR_LIMIT_MASK	(0x3f << USICx_CHy_RBCTR_LIMIT_OFFSET)

#define USICx_CHy_TRBSR_TEMPTY		BIT(11)
#define USICx_CHy_TRBSR_TFULL		BIT(12)

#endif
