obj-$(CONFIG_FB_FUJITSU_FDB)   := fdb.o
obj-$(CONFIG_FB_PICAPDC)	+= picapdc-fb.o f_mb8ac0300_dpi.o f_mb8ac0300_dvi.o
obj-$(CONFIG_FB_MB86S70)	+= iris-fb.o
obj-$(CONFIG_F_MIPIDSI1_LP)	+= f_mipidsi1_lp.o
obj-$(CONFIG_F_HDMI_TX14)	+= f_hdmi_tx14.o
obj-$(CONFIG_F_FPDL_TX)		+= f_fpdl_tx.o
obj-$(CONFIG_SN65DSI84)		+= sn65dsi84.o

iris-fb-y := mb86s70-fb.o iris-blitter.o
